// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthclient type in the database.
	Label = "oauth_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClientType holds the string denoting the client_type field in the database.
	FieldClientType = "client_type"
	// FieldRedirectUris holds the string denoting the redirect_uris field in the database.
	FieldRedirectUris = "redirect_uris"
	// FieldAllowedGrantTypes holds the string denoting the allowed_grant_types field in the database.
	FieldAllowedGrantTypes = "allowed_grant_types"
	// FieldAllowedScopes holds the string denoting the allowed_scopes field in the database.
	FieldAllowedScopes = "allowed_scopes"
	// FieldRequirePkce holds the string denoting the require_pkce field in the database.
	FieldRequirePkce = "require_pkce"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeOauthAuthorizationTransactions holds the string denoting the oauth_authorization_transactions edge name in mutations.
	EdgeOauthAuthorizationTransactions = "oauth_authorization_transactions"
	// EdgeOauthAuthorizationCodes holds the string denoting the oauth_authorization_codes edge name in mutations.
	EdgeOauthAuthorizationCodes = "oauth_authorization_codes"
	// EdgeOauthConsents holds the string denoting the oauth_consents edge name in mutations.
	EdgeOauthConsents = "oauth_consents"
	// EdgeOauthAccessTokens holds the string denoting the oauth_access_tokens edge name in mutations.
	EdgeOauthAccessTokens = "oauth_access_tokens"
	// EdgeOauthRefreshTokens holds the string denoting the oauth_refresh_tokens edge name in mutations.
	EdgeOauthRefreshTokens = "oauth_refresh_tokens"
	// EdgeOauthManagedAPIKeys holds the string denoting the oauth_managed_api_keys edge name in mutations.
	EdgeOauthManagedAPIKeys = "oauth_managed_api_keys"
	// Table holds the table name of the oauthclient in the database.
	Table = "oauth_clients"
	// OauthAuthorizationTransactionsTable is the table that holds the oauth_authorization_transactions relation/edge.
	OauthAuthorizationTransactionsTable = "oauth_authorization_transactions"
	// OauthAuthorizationTransactionsInverseTable is the table name for the OAuthAuthorizationTransaction entity.
	// It exists in this package in order to avoid circular dependency with the "oauthauthorizationtransaction" package.
	OauthAuthorizationTransactionsInverseTable = "oauth_authorization_transactions"
	// OauthAuthorizationTransactionsColumn is the table column denoting the oauth_authorization_transactions relation/edge.
	OauthAuthorizationTransactionsColumn = "client_id"
	// OauthAuthorizationCodesTable is the table that holds the oauth_authorization_codes relation/edge.
	OauthAuthorizationCodesTable = "oauth_authorization_codes"
	// OauthAuthorizationCodesInverseTable is the table name for the OAuthAuthorizationCode entity.
	// It exists in this package in order to avoid circular dependency with the "oauthauthorizationcode" package.
	OauthAuthorizationCodesInverseTable = "oauth_authorization_codes"
	// OauthAuthorizationCodesColumn is the table column denoting the oauth_authorization_codes relation/edge.
	OauthAuthorizationCodesColumn = "client_id"
	// OauthConsentsTable is the table that holds the oauth_consents relation/edge.
	OauthConsentsTable = "oauth_consents"
	// OauthConsentsInverseTable is the table name for the OAuthConsent entity.
	// It exists in this package in order to avoid circular dependency with the "oauthconsent" package.
	OauthConsentsInverseTable = "oauth_consents"
	// OauthConsentsColumn is the table column denoting the oauth_consents relation/edge.
	OauthConsentsColumn = "client_id"
	// OauthAccessTokensTable is the table that holds the oauth_access_tokens relation/edge.
	OauthAccessTokensTable = "oauth_access_tokens"
	// OauthAccessTokensInverseTable is the table name for the OAuthAccessToken entity.
	// It exists in this package in order to avoid circular dependency with the "oauthaccesstoken" package.
	OauthAccessTokensInverseTable = "oauth_access_tokens"
	// OauthAccessTokensColumn is the table column denoting the oauth_access_tokens relation/edge.
	OauthAccessTokensColumn = "client_id"
	// OauthRefreshTokensTable is the table that holds the oauth_refresh_tokens relation/edge.
	OauthRefreshTokensTable = "oauth_refresh_tokens"
	// OauthRefreshTokensInverseTable is the table name for the OAuthRefreshToken entity.
	// It exists in this package in order to avoid circular dependency with the "oauthrefreshtoken" package.
	OauthRefreshTokensInverseTable = "oauth_refresh_tokens"
	// OauthRefreshTokensColumn is the table column denoting the oauth_refresh_tokens relation/edge.
	OauthRefreshTokensColumn = "client_id"
	// OauthManagedAPIKeysTable is the table that holds the oauth_managed_api_keys relation/edge.
	OauthManagedAPIKeysTable = "oauth_managed_api_keys"
	// OauthManagedAPIKeysInverseTable is the table name for the OAuthManagedAPIKey entity.
	// It exists in this package in order to avoid circular dependency with the "oauthmanagedapikey" package.
	OauthManagedAPIKeysInverseTable = "oauth_managed_api_keys"
	// OauthManagedAPIKeysColumn is the table column denoting the oauth_managed_api_keys relation/edge.
	OauthManagedAPIKeysColumn = "client_id"
)

// Columns holds all SQL columns for oauthclient fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldClientID,
	FieldName,
	FieldClientType,
	FieldRedirectUris,
	FieldAllowedGrantTypes,
	FieldAllowedScopes,
	FieldRequirePkce,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultClientType holds the default value on creation for the "client_type" field.
	DefaultClientType string
	// ClientTypeValidator is a validator for the "client_type" field. It is called by the builders before save.
	ClientTypeValidator func(string) error
	// DefaultRedirectUris holds the default value on creation for the "redirect_uris" field.
	DefaultRedirectUris func() []string
	// DefaultAllowedGrantTypes holds the default value on creation for the "allowed_grant_types" field.
	DefaultAllowedGrantTypes func() []string
	// DefaultAllowedScopes holds the default value on creation for the "allowed_scopes" field.
	DefaultAllowedScopes func() []string
	// DefaultRequirePkce holds the default value on creation for the "require_pkce" field.
	DefaultRequirePkce bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the OAuthClient queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByClientType orders the results by the client_type field.
func ByClientType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientType, opts...).ToFunc()
}

// ByRequirePkce orders the results by the require_pkce field.
func ByRequirePkce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequirePkce, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOauthAuthorizationTransactionsCount orders the results by oauth_authorization_transactions count.
func ByOauthAuthorizationTransactionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthAuthorizationTransactionsStep(), opts...)
	}
}

// ByOauthAuthorizationTransactions orders the results by oauth_authorization_transactions terms.
func ByOauthAuthorizationTransactions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthAuthorizationTransactionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOauthAuthorizationCodesCount orders the results by oauth_authorization_codes count.
func ByOauthAuthorizationCodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthAuthorizationCodesStep(), opts...)
	}
}

// ByOauthAuthorizationCodes orders the results by oauth_authorization_codes terms.
func ByOauthAuthorizationCodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthAuthorizationCodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOauthConsentsCount orders the results by oauth_consents count.
func ByOauthConsentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthConsentsStep(), opts...)
	}
}

// ByOauthConsents orders the results by oauth_consents terms.
func ByOauthConsents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthConsentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOauthAccessTokensCount orders the results by oauth_access_tokens count.
func ByOauthAccessTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthAccessTokensStep(), opts...)
	}
}

// ByOauthAccessTokens orders the results by oauth_access_tokens terms.
func ByOauthAccessTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthAccessTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOauthRefreshTokensCount orders the results by oauth_refresh_tokens count.
func ByOauthRefreshTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthRefreshTokensStep(), opts...)
	}
}

// ByOauthRefreshTokens orders the results by oauth_refresh_tokens terms.
func ByOauthRefreshTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthRefreshTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOauthManagedAPIKeysCount orders the results by oauth_managed_api_keys count.
func ByOauthManagedAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthManagedAPIKeysStep(), opts...)
	}
}

// ByOauthManagedAPIKeys orders the results by oauth_managed_api_keys terms.
func ByOauthManagedAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthManagedAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOauthAuthorizationTransactionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthAuthorizationTransactionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthAuthorizationTransactionsTable, OauthAuthorizationTransactionsColumn),
	)
}
func newOauthAuthorizationCodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthAuthorizationCodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthAuthorizationCodesTable, OauthAuthorizationCodesColumn),
	)
}
func newOauthConsentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthConsentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthConsentsTable, OauthConsentsColumn),
	)
}
func newOauthAccessTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthAccessTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthAccessTokensTable, OauthAccessTokensColumn),
	)
}
func newOauthRefreshTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthRefreshTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthRefreshTokensTable, OauthRefreshTokensColumn),
	)
}
func newOauthManagedAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthManagedAPIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthManagedAPIKeysTable, OauthManagedAPIKeysColumn),
	)
}
