// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthaccesstoken"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationcode"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationtransaction"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthconsent"
	"github.com/Wei-Shaw/sub2api/ent/oauthmanagedapikey"
	"github.com/Wei-Shaw/sub2api/ent/oauthrefreshtoken"
)

// OAuthClientCreate is the builder for creating a OAuthClient entity.
type OAuthClientCreate struct {
	config
	mutation *OAuthClientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthClientCreate) SetCreatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableCreatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthClientCreate) SetUpdatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableUpdatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthClientCreate) SetClientID(v string) *OAuthClientCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OAuthClientCreate) SetName(v string) *OAuthClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetClientType sets the "client_type" field.
func (_c *OAuthClientCreate) SetClientType(v string) *OAuthClientCreate {
	_c.mutation.SetClientType(v)
	return _c
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableClientType(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetClientType(*v)
	}
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *OAuthClientCreate) SetRedirectUris(v []string) *OAuthClientCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetAllowedGrantTypes sets the "allowed_grant_types" field.
func (_c *OAuthClientCreate) SetAllowedGrantTypes(v []string) *OAuthClientCreate {
	_c.mutation.SetAllowedGrantTypes(v)
	return _c
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_c *OAuthClientCreate) SetAllowedScopes(v []string) *OAuthClientCreate {
	_c.mutation.SetAllowedScopes(v)
	return _c
}

// SetRequirePkce sets the "require_pkce" field.
func (_c *OAuthClientCreate) SetRequirePkce(v bool) *OAuthClientCreate {
	_c.mutation.SetRequirePkce(v)
	return _c
}

// SetNillableRequirePkce sets the "require_pkce" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableRequirePkce(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetRequirePkce(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OAuthClientCreate) SetStatus(v string) *OAuthClientCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableStatus(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddOauthAuthorizationTransactionIDs adds the "oauth_authorization_transactions" edge to the OAuthAuthorizationTransaction entity by IDs.
func (_c *OAuthClientCreate) AddOauthAuthorizationTransactionIDs(ids ...int64) *OAuthClientCreate {
	_c.mutation.AddOauthAuthorizationTransactionIDs(ids...)
	return _c
}

// AddOauthAuthorizationTransactions adds the "oauth_authorization_transactions" edges to the OAuthAuthorizationTransaction entity.
func (_c *OAuthClientCreate) AddOauthAuthorizationTransactions(v ...*OAuthAuthorizationTransaction) *OAuthClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthAuthorizationTransactionIDs(ids...)
}

// AddOauthAuthorizationCodeIDs adds the "oauth_authorization_codes" edge to the OAuthAuthorizationCode entity by IDs.
func (_c *OAuthClientCreate) AddOauthAuthorizationCodeIDs(ids ...int64) *OAuthClientCreate {
	_c.mutation.AddOauthAuthorizationCodeIDs(ids...)
	return _c
}

// AddOauthAuthorizationCodes adds the "oauth_authorization_codes" edges to the OAuthAuthorizationCode entity.
func (_c *OAuthClientCreate) AddOauthAuthorizationCodes(v ...*OAuthAuthorizationCode) *OAuthClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthAuthorizationCodeIDs(ids...)
}

// AddOauthConsentIDs adds the "oauth_consents" edge to the OAuthConsent entity by IDs.
func (_c *OAuthClientCreate) AddOauthConsentIDs(ids ...int64) *OAuthClientCreate {
	_c.mutation.AddOauthConsentIDs(ids...)
	return _c
}

// AddOauthConsents adds the "oauth_consents" edges to the OAuthConsent entity.
func (_c *OAuthClientCreate) AddOauthConsents(v ...*OAuthConsent) *OAuthClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthConsentIDs(ids...)
}

// AddOauthAccessTokenIDs adds the "oauth_access_tokens" edge to the OAuthAccessToken entity by IDs.
func (_c *OAuthClientCreate) AddOauthAccessTokenIDs(ids ...int64) *OAuthClientCreate {
	_c.mutation.AddOauthAccessTokenIDs(ids...)
	return _c
}

// AddOauthAccessTokens adds the "oauth_access_tokens" edges to the OAuthAccessToken entity.
func (_c *OAuthClientCreate) AddOauthAccessTokens(v ...*OAuthAccessToken) *OAuthClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthAccessTokenIDs(ids...)
}

// AddOauthRefreshTokenIDs adds the "oauth_refresh_tokens" edge to the OAuthRefreshToken entity by IDs.
func (_c *OAuthClientCreate) AddOauthRefreshTokenIDs(ids ...int64) *OAuthClientCreate {
	_c.mutation.AddOauthRefreshTokenIDs(ids...)
	return _c
}

// AddOauthRefreshTokens adds the "oauth_refresh_tokens" edges to the OAuthRefreshToken entity.
func (_c *OAuthClientCreate) AddOauthRefreshTokens(v ...*OAuthRefreshToken) *OAuthClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthRefreshTokenIDs(ids...)
}

// AddOauthManagedAPIKeyIDs adds the "oauth_managed_api_keys" edge to the OAuthManagedAPIKey entity by IDs.
func (_c *OAuthClientCreate) AddOauthManagedAPIKeyIDs(ids ...int64) *OAuthClientCreate {
	_c.mutation.AddOauthManagedAPIKeyIDs(ids...)
	return _c
}

// AddOauthManagedAPIKeys adds the "oauth_managed_api_keys" edges to the OAuthManagedAPIKey entity.
func (_c *OAuthClientCreate) AddOauthManagedAPIKeys(v ...*OAuthManagedAPIKey) *OAuthClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthManagedAPIKeyIDs(ids...)
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_c *OAuthClientCreate) Mutation() *OAuthClientMutation {
	return _c.mutation
}

// Save creates the OAuthClient in the database.
func (_c *OAuthClientCreate) Save(ctx context.Context) (*OAuthClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthClientCreate) SaveX(ctx context.Context) *OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthClientCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ClientType(); !ok {
		v := oauthclient.DefaultClientType
		_c.mutation.SetClientType(v)
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		v := oauthclient.DefaultRedirectUris()
		_c.mutation.SetRedirectUris(v)
	}
	if _, ok := _c.mutation.AllowedGrantTypes(); !ok {
		v := oauthclient.DefaultAllowedGrantTypes()
		_c.mutation.SetAllowedGrantTypes(v)
	}
	if _, ok := _c.mutation.AllowedScopes(); !ok {
		v := oauthclient.DefaultAllowedScopes()
		_c.mutation.SetAllowedScopes(v)
	}
	if _, ok := _c.mutation.RequirePkce(); !ok {
		v := oauthclient.DefaultRequirePkce
		_c.mutation.SetRequirePkce(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := oauthclient.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthClientCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthClient.updated_at"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthClient.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientType(); !ok {
		return &ValidationError{Name: "client_type", err: errors.New(`ent: missing required field "OAuthClient.client_type"`)}
	}
	if v, ok := _c.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		return &ValidationError{Name: "redirect_uris", err: errors.New(`ent: missing required field "OAuthClient.redirect_uris"`)}
	}
	if _, ok := _c.mutation.AllowedGrantTypes(); !ok {
		return &ValidationError{Name: "allowed_grant_types", err: errors.New(`ent: missing required field "OAuthClient.allowed_grant_types"`)}
	}
	if _, ok := _c.mutation.AllowedScopes(); !ok {
		return &ValidationError{Name: "allowed_scopes", err: errors.New(`ent: missing required field "OAuthClient.allowed_scopes"`)}
	}
	if _, ok := _c.mutation.RequirePkce(); !ok {
		return &ValidationError{Name: "require_pkce", err: errors.New(`ent: missing required field "OAuthClient.require_pkce"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OAuthClient.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := oauthclient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.status": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthClientCreate) sqlSave(ctx context.Context) (*OAuthClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthClientCreate) createSpec() (*OAuthClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthclient.Table, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeString, value)
		_node.ClientType = value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.AllowedGrantTypes(); ok {
		_spec.SetField(oauthclient.FieldAllowedGrantTypes, field.TypeJSON, value)
		_node.AllowedGrantTypes = value
	}
	if value, ok := _c.mutation.AllowedScopes(); ok {
		_spec.SetField(oauthclient.FieldAllowedScopes, field.TypeJSON, value)
		_node.AllowedScopes = value
	}
	if value, ok := _c.mutation.RequirePkce(); ok {
		_spec.SetField(oauthclient.FieldRequirePkce, field.TypeBool, value)
		_node.RequirePkce = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(oauthclient.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.OauthAuthorizationTransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.OauthAuthorizationTransactionsTable,
			Columns: []string{oauthclient.OauthAuthorizationTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthauthorizationtransaction.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OauthAuthorizationCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.OauthAuthorizationCodesTable,
			Columns: []string{oauthclient.OauthAuthorizationCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OauthConsentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.OauthConsentsTable,
			Columns: []string{oauthclient.OauthConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OauthAccessTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.OauthAccessTokensTable,
			Columns: []string{oauthclient.OauthAccessTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OauthRefreshTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.OauthRefreshTokensTable,
			Columns: []string{oauthclient.OauthRefreshTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OauthManagedAPIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.OauthManagedAPIKeysTable,
			Columns: []string{oauthclient.OauthManagedAPIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthmanagedapikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthClient.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthClientUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthClientCreate) OnConflict(opts ...sql.ConflictOption) *OAuthClientUpsertOne {
	_c.conflict = opts
	return &OAuthClientUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthClientCreate) OnConflictColumns(columns ...string) *OAuthClientUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthClientUpsertOne{
		create: _c,
	}
}

type (
	// OAuthClientUpsertOne is the builder for "upsert"-ing
	//  one OAuthClient node.
	OAuthClientUpsertOne struct {
		create *OAuthClientCreate
	}

	// OAuthClientUpsert is the "OnConflict" setter.
	OAuthClientUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsert) SetUpdatedAt(v time.Time) *OAuthClientUpsert {
	u.Set(oauthclient.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateUpdatedAt() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldUpdatedAt)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsert) SetClientID(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientID() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientID)
	return u
}

// SetName sets the "name" field.
func (u *OAuthClientUpsert) SetName(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateName() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldName)
	return u
}

// SetClientType sets the "client_type" field.
func (u *OAuthClientUpsert) SetClientType(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientType, v)
	return u
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientType() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientType)
	return u
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsert) SetRedirectUris(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldRedirectUris, v)
	return u
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateRedirectUris() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldRedirectUris)
	return u
}

// SetAllowedGrantTypes sets the "allowed_grant_types" field.
func (u *OAuthClientUpsert) SetAllowedGrantTypes(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowedGrantTypes, v)
	return u
}

// UpdateAllowedGrantTypes sets the "allowed_grant_types" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowedGrantTypes() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowedGrantTypes)
	return u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (u *OAuthClientUpsert) SetAllowedScopes(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowedScopes, v)
	return u
}

// UpdateAllowedScopes sets the "allowed_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowedScopes() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowedScopes)
	return u
}

// SetRequirePkce sets the "require_pkce" field.
func (u *OAuthClientUpsert) SetRequirePkce(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldRequirePkce, v)
	return u
}

// UpdateRequirePkce sets the "require_pkce" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateRequirePkce() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldRequirePkce)
	return u
}

// SetStatus sets the "status" field.
func (u *OAuthClientUpsert) SetStatus(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateStatus() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthClientUpsertOne) UpdateNewValues() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthclient.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthClientUpsertOne) Ignore() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthClientUpsertOne) DoNothing() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthClientCreate.OnConflict
// documentation for more info.
func (u *OAuthClientUpsertOne) Update(set func(*OAuthClientUpsert)) *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsertOne) SetUpdatedAt(v time.Time) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateUpdatedAt() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsertOne) SetClientID(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientID() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientID()
	})
}

// SetName sets the "name" field.
func (u *OAuthClientUpsertOne) SetName(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateName() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateName()
	})
}

// SetClientType sets the "client_type" field.
func (u *OAuthClientUpsertOne) SetClientType(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientType(v)
	})
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientType() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientType()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsertOne) SetRedirectUris(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateRedirectUris() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowedGrantTypes sets the "allowed_grant_types" field.
func (u *OAuthClientUpsertOne) SetAllowedGrantTypes(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedGrantTypes(v)
	})
}

// UpdateAllowedGrantTypes sets the "allowed_grant_types" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowedGrantTypes() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedGrantTypes()
	})
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (u *OAuthClientUpsertOne) SetAllowedScopes(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedScopes(v)
	})
}

// UpdateAllowedScopes sets the "allowed_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowedScopes() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedScopes()
	})
}

// SetRequirePkce sets the "require_pkce" field.
func (u *OAuthClientUpsertOne) SetRequirePkce(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRequirePkce(v)
	})
}

// UpdateRequirePkce sets the "require_pkce" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateRequirePkce() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRequirePkce()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthClientUpsertOne) SetStatus(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateStatus() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OAuthClientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthClientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthClientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthClientUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthClientUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthClientCreateBulk is the builder for creating many OAuthClient entities in bulk.
type OAuthClientCreateBulk struct {
	config
	err      error
	builders []*OAuthClientCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthClient entities in the database.
func (_c *OAuthClientCreateBulk) Save(ctx context.Context) ([]*OAuthClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) SaveX(ctx context.Context) []*OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthClient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthClientUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthClientCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthClientUpsertBulk {
	_c.conflict = opts
	return &OAuthClientUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthClientCreateBulk) OnConflictColumns(columns ...string) *OAuthClientUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthClientUpsertBulk{
		create: _c,
	}
}

// OAuthClientUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthClient nodes.
type OAuthClientUpsertBulk struct {
	create *OAuthClientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthClientUpsertBulk) UpdateNewValues() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthclient.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthClientUpsertBulk) Ignore() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthClientUpsertBulk) DoNothing() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthClientCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthClientUpsertBulk) Update(set func(*OAuthClientUpsert)) *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsertBulk) SetUpdatedAt(v time.Time) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateUpdatedAt() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsertBulk) SetClientID(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientID() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientID()
	})
}

// SetName sets the "name" field.
func (u *OAuthClientUpsertBulk) SetName(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateName() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateName()
	})
}

// SetClientType sets the "client_type" field.
func (u *OAuthClientUpsertBulk) SetClientType(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientType(v)
	})
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientType() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientType()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsertBulk) SetRedirectUris(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateRedirectUris() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowedGrantTypes sets the "allowed_grant_types" field.
func (u *OAuthClientUpsertBulk) SetAllowedGrantTypes(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedGrantTypes(v)
	})
}

// UpdateAllowedGrantTypes sets the "allowed_grant_types" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowedGrantTypes() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedGrantTypes()
	})
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (u *OAuthClientUpsertBulk) SetAllowedScopes(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedScopes(v)
	})
}

// UpdateAllowedScopes sets the "allowed_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowedScopes() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedScopes()
	})
}

// SetRequirePkce sets the "require_pkce" field.
func (u *OAuthClientUpsertBulk) SetRequirePkce(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRequirePkce(v)
	})
}

// UpdateRequirePkce sets the "require_pkce" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateRequirePkce() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRequirePkce()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthClientUpsertBulk) SetStatus(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateStatus() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OAuthClientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthClientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthClientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthClientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
