// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthmanagedapikey"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthManagedAPIKey is the model entity for the OAuthManagedAPIKey schema.
type OAuthManagedAPIKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Internal FK to oauth_clients.id.
	ClientID int64 `json:"client_id,omitempty"`
	// Internal FK to api_keys.id.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthManagedAPIKeyQuery when eager-loading is set.
	Edges        OAuthManagedAPIKeyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthManagedAPIKeyEdges holds the relations/edges for other nodes in the graph.
type OAuthManagedAPIKeyEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Client holds the value of the client edge.
	Client *OAuthClient `json:"client,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthManagedAPIKeyEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthManagedAPIKeyEdges) ClientOrErr() (*OAuthClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: oauthclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthManagedAPIKeyEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthManagedAPIKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthmanagedapikey.FieldID, oauthmanagedapikey.FieldUserID, oauthmanagedapikey.FieldClientID, oauthmanagedapikey.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case oauthmanagedapikey.FieldCreatedAt, oauthmanagedapikey.FieldUpdatedAt, oauthmanagedapikey.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthManagedAPIKey fields.
func (_m *OAuthManagedAPIKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthmanagedapikey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthmanagedapikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthmanagedapikey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthmanagedapikey.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case oauthmanagedapikey.FieldClientID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.Int64
			}
		case oauthmanagedapikey.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case oauthmanagedapikey.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthManagedAPIKey.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthManagedAPIKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OAuthManagedAPIKey entity.
func (_m *OAuthManagedAPIKey) QueryUser() *UserQuery {
	return NewOAuthManagedAPIKeyClient(_m.config).QueryUser(_m)
}

// QueryClient queries the "client" edge of the OAuthManagedAPIKey entity.
func (_m *OAuthManagedAPIKey) QueryClient() *OAuthClientQuery {
	return NewOAuthManagedAPIKeyClient(_m.config).QueryClient(_m)
}

// QueryAPIKey queries the "api_key" edge of the OAuthManagedAPIKey entity.
func (_m *OAuthManagedAPIKey) QueryAPIKey() *APIKeyQuery {
	return NewOAuthManagedAPIKeyClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this OAuthManagedAPIKey.
// Note that you need to call OAuthManagedAPIKey.Unwrap() before calling this method if this OAuthManagedAPIKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthManagedAPIKey) Update() *OAuthManagedAPIKeyUpdateOne {
	return NewOAuthManagedAPIKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthManagedAPIKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthManagedAPIKey) Unwrap() *OAuthManagedAPIKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthManagedAPIKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthManagedAPIKey) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthManagedAPIKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthManagedAPIKeys is a parsable slice of OAuthManagedAPIKey.
type OAuthManagedAPIKeys []*OAuthManagedAPIKey
