// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthconsent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthConsentCreate is the builder for creating a OAuthConsent entity.
type OAuthConsentCreate struct {
	config
	mutation *OAuthConsentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthConsentCreate) SetCreatedAt(v time.Time) *OAuthConsentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableCreatedAt(v *time.Time) *OAuthConsentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthConsentCreate) SetUpdatedAt(v time.Time) *OAuthConsentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableUpdatedAt(v *time.Time) *OAuthConsentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthConsentCreate) SetUserID(v int64) *OAuthConsentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthConsentCreate) SetClientID(v int64) *OAuthConsentCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthConsentCreate) SetScopes(v []string) *OAuthConsentCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *OAuthConsentCreate) SetRevokedAt(v time.Time) *OAuthConsentCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableRevokedAt(v *time.Time) *OAuthConsentCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OAuthConsentCreate) SetUser(v *User) *OAuthConsentCreate {
	return _c.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_c *OAuthConsentCreate) SetClient(v *OAuthClient) *OAuthConsentCreate {
	return _c.SetClientID(v.ID)
}

// Mutation returns the OAuthConsentMutation object of the builder.
func (_c *OAuthConsentCreate) Mutation() *OAuthConsentMutation {
	return _c.mutation
}

// Save creates the OAuthConsent in the database.
func (_c *OAuthConsentCreate) Save(ctx context.Context) (*OAuthConsent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthConsentCreate) SaveX(ctx context.Context) *OAuthConsent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthConsentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthConsentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthConsentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthconsent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthconsent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oauthconsent.DefaultScopes()
		_c.mutation.SetScopes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthConsentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthConsent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthConsent.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthConsent.user_id"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthConsent.client_id"`)}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthConsent.scopes"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OAuthConsent.user"`)}
	}
	if len(_c.mutation.ClientIDs()) == 0 {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required edge "OAuthConsent.client"`)}
	}
	return nil
}

func (_c *OAuthConsentCreate) sqlSave(ctx context.Context) (*OAuthConsent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthConsentCreate) createSpec() (*OAuthConsent, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthConsent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthconsent.Table, sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthconsent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthconsent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthconsent.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(oauthconsent.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.UserTable,
			Columns: []string{oauthconsent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.ClientTable,
			Columns: []string{oauthconsent.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthConsent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthConsentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthConsentCreate) OnConflict(opts ...sql.ConflictOption) *OAuthConsentUpsertOne {
	_c.conflict = opts
	return &OAuthConsentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthConsent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthConsentCreate) OnConflictColumns(columns ...string) *OAuthConsentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthConsentUpsertOne{
		create: _c,
	}
}

type (
	// OAuthConsentUpsertOne is the builder for "upsert"-ing
	//  one OAuthConsent node.
	OAuthConsentUpsertOne struct {
		create *OAuthConsentCreate
	}

	// OAuthConsentUpsert is the "OnConflict" setter.
	OAuthConsentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthConsentUpsert) SetUpdatedAt(v time.Time) *OAuthConsentUpsert {
	u.Set(oauthconsent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthConsentUpsert) UpdateUpdatedAt() *OAuthConsentUpsert {
	u.SetExcluded(oauthconsent.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OAuthConsentUpsert) SetUserID(v int64) *OAuthConsentUpsert {
	u.Set(oauthconsent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthConsentUpsert) UpdateUserID() *OAuthConsentUpsert {
	u.SetExcluded(oauthconsent.FieldUserID)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthConsentUpsert) SetClientID(v int64) *OAuthConsentUpsert {
	u.Set(oauthconsent.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthConsentUpsert) UpdateClientID() *OAuthConsentUpsert {
	u.SetExcluded(oauthconsent.FieldClientID)
	return u
}

// SetScopes sets the "scopes" field.
func (u *OAuthConsentUpsert) SetScopes(v []string) *OAuthConsentUpsert {
	u.Set(oauthconsent.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthConsentUpsert) UpdateScopes() *OAuthConsentUpsert {
	u.SetExcluded(oauthconsent.FieldScopes)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *OAuthConsentUpsert) SetRevokedAt(v time.Time) *OAuthConsentUpsert {
	u.Set(oauthconsent.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *OAuthConsentUpsert) UpdateRevokedAt() *OAuthConsentUpsert {
	u.SetExcluded(oauthconsent.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *OAuthConsentUpsert) ClearRevokedAt() *OAuthConsentUpsert {
	u.SetNull(oauthconsent.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthConsent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthConsentUpsertOne) UpdateNewValues() *OAuthConsentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthconsent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthConsent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthConsentUpsertOne) Ignore() *OAuthConsentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthConsentUpsertOne) DoNothing() *OAuthConsentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthConsentCreate.OnConflict
// documentation for more info.
func (u *OAuthConsentUpsertOne) Update(set func(*OAuthConsentUpsert)) *OAuthConsentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthConsentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthConsentUpsertOne) SetUpdatedAt(v time.Time) *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthConsentUpsertOne) UpdateUpdatedAt() *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthConsentUpsertOne) SetUserID(v int64) *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthConsentUpsertOne) UpdateUserID() *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateUserID()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthConsentUpsertOne) SetClientID(v int64) *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthConsentUpsertOne) UpdateClientID() *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthConsentUpsertOne) SetScopes(v []string) *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthConsentUpsertOne) UpdateScopes() *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateScopes()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *OAuthConsentUpsertOne) SetRevokedAt(v time.Time) *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *OAuthConsentUpsertOne) UpdateRevokedAt() *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *OAuthConsentUpsertOne) ClearRevokedAt() *OAuthConsentUpsertOne {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *OAuthConsentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthConsentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthConsentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthConsentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthConsentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthConsentCreateBulk is the builder for creating many OAuthConsent entities in bulk.
type OAuthConsentCreateBulk struct {
	config
	err      error
	builders []*OAuthConsentCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthConsent entities in the database.
func (_c *OAuthConsentCreateBulk) Save(ctx context.Context) ([]*OAuthConsent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthConsent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthConsentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthConsentCreateBulk) SaveX(ctx context.Context) []*OAuthConsent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthConsentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthConsentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthConsent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthConsentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthConsentCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthConsentUpsertBulk {
	_c.conflict = opts
	return &OAuthConsentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthConsent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthConsentCreateBulk) OnConflictColumns(columns ...string) *OAuthConsentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthConsentUpsertBulk{
		create: _c,
	}
}

// OAuthConsentUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthConsent nodes.
type OAuthConsentUpsertBulk struct {
	create *OAuthConsentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthConsent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthConsentUpsertBulk) UpdateNewValues() *OAuthConsentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthconsent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthConsent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthConsentUpsertBulk) Ignore() *OAuthConsentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthConsentUpsertBulk) DoNothing() *OAuthConsentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthConsentCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthConsentUpsertBulk) Update(set func(*OAuthConsentUpsert)) *OAuthConsentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthConsentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthConsentUpsertBulk) SetUpdatedAt(v time.Time) *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthConsentUpsertBulk) UpdateUpdatedAt() *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthConsentUpsertBulk) SetUserID(v int64) *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthConsentUpsertBulk) UpdateUserID() *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateUserID()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthConsentUpsertBulk) SetClientID(v int64) *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthConsentUpsertBulk) UpdateClientID() *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthConsentUpsertBulk) SetScopes(v []string) *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthConsentUpsertBulk) UpdateScopes() *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateScopes()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *OAuthConsentUpsertBulk) SetRevokedAt(v time.Time) *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *OAuthConsentUpsertBulk) UpdateRevokedAt() *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *OAuthConsentUpsertBulk) ClearRevokedAt() *OAuthConsentUpsertBulk {
	return u.Update(func(s *OAuthConsentUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *OAuthConsentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthConsentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthConsentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthConsentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
