// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthmanagedapikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthManagedAPIKeyUpdate is the builder for updating OAuthManagedAPIKey entities.
type OAuthManagedAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthManagedAPIKeyMutation
}

// Where appends a list predicates to the OAuthManagedAPIKeyUpdate builder.
func (_u *OAuthManagedAPIKeyUpdate) Where(ps ...predicate.OAuthManagedAPIKey) *OAuthManagedAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthManagedAPIKeyUpdate) SetUpdatedAt(v time.Time) *OAuthManagedAPIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthManagedAPIKeyUpdate) SetUserID(v int64) *OAuthManagedAPIKeyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdate) SetNillableUserID(v *int64) *OAuthManagedAPIKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthManagedAPIKeyUpdate) SetClientID(v int64) *OAuthManagedAPIKeyUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdate) SetNillableClientID(v *int64) *OAuthManagedAPIKeyUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OAuthManagedAPIKeyUpdate) SetAPIKeyID(v int64) *OAuthManagedAPIKeyUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdate) SetNillableAPIKeyID(v *int64) *OAuthManagedAPIKeyUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthManagedAPIKeyUpdate) SetRevokedAt(v time.Time) *OAuthManagedAPIKeyUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdate) SetNillableRevokedAt(v *time.Time) *OAuthManagedAPIKeyUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthManagedAPIKeyUpdate) ClearRevokedAt() *OAuthManagedAPIKeyUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthManagedAPIKeyUpdate) SetUser(v *User) *OAuthManagedAPIKeyUpdate {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthManagedAPIKeyUpdate) SetClient(v *OAuthClient) *OAuthManagedAPIKeyUpdate {
	return _u.SetClientID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *OAuthManagedAPIKeyUpdate) SetAPIKey(v *APIKey) *OAuthManagedAPIKeyUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the OAuthManagedAPIKeyMutation object of the builder.
func (_u *OAuthManagedAPIKeyUpdate) Mutation() *OAuthManagedAPIKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthManagedAPIKeyUpdate) ClearUser() *OAuthManagedAPIKeyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthManagedAPIKeyUpdate) ClearClient() *OAuthManagedAPIKeyUpdate {
	_u.mutation.ClearClient()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *OAuthManagedAPIKeyUpdate) ClearAPIKey() *OAuthManagedAPIKeyUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthManagedAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthManagedAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthManagedAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthManagedAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthManagedAPIKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthmanagedapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthManagedAPIKeyUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthManagedAPIKey.user"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthManagedAPIKey.client"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthManagedAPIKey.api_key"`)
	}
	return nil
}

func (_u *OAuthManagedAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthmanagedapikey.Table, oauthmanagedapikey.Columns, sqlgraph.NewFieldSpec(oauthmanagedapikey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthmanagedapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthmanagedapikey.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthmanagedapikey.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.UserTable,
			Columns: []string{oauthmanagedapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.UserTable,
			Columns: []string{oauthmanagedapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.ClientTable,
			Columns: []string{oauthmanagedapikey.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.ClientTable,
			Columns: []string{oauthmanagedapikey.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.APIKeyTable,
			Columns: []string{oauthmanagedapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.APIKeyTable,
			Columns: []string{oauthmanagedapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthmanagedapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthManagedAPIKeyUpdateOne is the builder for updating a single OAuthManagedAPIKey entity.
type OAuthManagedAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthManagedAPIKeyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthManagedAPIKeyUpdateOne) SetUpdatedAt(v time.Time) *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthManagedAPIKeyUpdateOne) SetUserID(v int64) *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdateOne) SetNillableUserID(v *int64) *OAuthManagedAPIKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthManagedAPIKeyUpdateOne) SetClientID(v int64) *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdateOne) SetNillableClientID(v *int64) *OAuthManagedAPIKeyUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OAuthManagedAPIKeyUpdateOne) SetAPIKeyID(v int64) *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdateOne) SetNillableAPIKeyID(v *int64) *OAuthManagedAPIKeyUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthManagedAPIKeyUpdateOne) SetRevokedAt(v time.Time) *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthManagedAPIKeyUpdateOne) SetNillableRevokedAt(v *time.Time) *OAuthManagedAPIKeyUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthManagedAPIKeyUpdateOne) ClearRevokedAt() *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthManagedAPIKeyUpdateOne) SetUser(v *User) *OAuthManagedAPIKeyUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthManagedAPIKeyUpdateOne) SetClient(v *OAuthClient) *OAuthManagedAPIKeyUpdateOne {
	return _u.SetClientID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *OAuthManagedAPIKeyUpdateOne) SetAPIKey(v *APIKey) *OAuthManagedAPIKeyUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the OAuthManagedAPIKeyMutation object of the builder.
func (_u *OAuthManagedAPIKeyUpdateOne) Mutation() *OAuthManagedAPIKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthManagedAPIKeyUpdateOne) ClearUser() *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthManagedAPIKeyUpdateOne) ClearClient() *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *OAuthManagedAPIKeyUpdateOne) ClearAPIKey() *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the OAuthManagedAPIKeyUpdate builder.
func (_u *OAuthManagedAPIKeyUpdateOne) Where(ps ...predicate.OAuthManagedAPIKey) *OAuthManagedAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthManagedAPIKeyUpdateOne) Select(field string, fields ...string) *OAuthManagedAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthManagedAPIKey entity.
func (_u *OAuthManagedAPIKeyUpdateOne) Save(ctx context.Context) (*OAuthManagedAPIKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthManagedAPIKeyUpdateOne) SaveX(ctx context.Context) *OAuthManagedAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthManagedAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthManagedAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthManagedAPIKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthmanagedapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthManagedAPIKeyUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthManagedAPIKey.user"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthManagedAPIKey.client"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthManagedAPIKey.api_key"`)
	}
	return nil
}

func (_u *OAuthManagedAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *OAuthManagedAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthmanagedapikey.Table, oauthmanagedapikey.Columns, sqlgraph.NewFieldSpec(oauthmanagedapikey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthManagedAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthmanagedapikey.FieldID)
		for _, f := range fields {
			if !oauthmanagedapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthmanagedapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthmanagedapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthmanagedapikey.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthmanagedapikey.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.UserTable,
			Columns: []string{oauthmanagedapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.UserTable,
			Columns: []string{oauthmanagedapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.ClientTable,
			Columns: []string{oauthmanagedapikey.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.ClientTable,
			Columns: []string{oauthmanagedapikey.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.APIKeyTable,
			Columns: []string{oauthmanagedapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthmanagedapikey.APIKeyTable,
			Columns: []string{oauthmanagedapikey.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthManagedAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthmanagedapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
