// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationtransaction"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthAuthorizationTransaction is the model entity for the OAuthAuthorizationTransaction schema.
type OAuthAuthorizationTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TransactionID holds the value of the "transaction_id" field.
	TransactionID string `json:"transaction_id,omitempty"`
	// RedirectURI holds the value of the "redirect_uri" field.
	RedirectURI string `json:"redirect_uri,omitempty"`
	// RequestedScopes holds the value of the "requested_scopes" field.
	RequestedScopes []string `json:"requested_scopes,omitempty"`
	// Original OAuth state echoed back to the client; never logged.
	State string `json:"state,omitempty"`
	// CodeChallenge holds the value of the "code_challenge" field.
	CodeChallenge string `json:"code_challenge,omitempty"`
	// CodeChallengeMethod holds the value of the "code_challenge_method" field.
	CodeChallengeMethod string `json:"code_challenge_method,omitempty"`
	// BrowserSessionHash holds the value of the "browser_session_hash" field.
	BrowserSessionHash string `json:"browser_session_hash,omitempty"`
	// CsrfTokenHash holds the value of the "csrf_token_hash" field.
	CsrfTokenHash string `json:"csrf_token_hash,omitempty"`
	// Populated after the user authenticates; nullable until login completes.
	UserID *int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// Internal FK to oauth_clients.id, not the external client_id string.
	ClientID int64 `json:"client_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthAuthorizationTransactionQuery when eager-loading is set.
	Edges        OAuthAuthorizationTransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthAuthorizationTransactionEdges holds the relations/edges for other nodes in the graph.
type OAuthAuthorizationTransactionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Client holds the value of the client edge.
	Client *OAuthClient `json:"client,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthAuthorizationTransactionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthAuthorizationTransactionEdges) ClientOrErr() (*OAuthClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: oauthclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthAuthorizationTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthauthorizationtransaction.FieldRequestedScopes:
			values[i] = new([]byte)
		case oauthauthorizationtransaction.FieldID, oauthauthorizationtransaction.FieldUserID, oauthauthorizationtransaction.FieldClientID:
			values[i] = new(sql.NullInt64)
		case oauthauthorizationtransaction.FieldTransactionID, oauthauthorizationtransaction.FieldRedirectURI, oauthauthorizationtransaction.FieldState, oauthauthorizationtransaction.FieldCodeChallenge, oauthauthorizationtransaction.FieldCodeChallengeMethod, oauthauthorizationtransaction.FieldBrowserSessionHash, oauthauthorizationtransaction.FieldCsrfTokenHash, oauthauthorizationtransaction.FieldStatus:
			values[i] = new(sql.NullString)
		case oauthauthorizationtransaction.FieldCreatedAt, oauthauthorizationtransaction.FieldUpdatedAt, oauthauthorizationtransaction.FieldExpiresAt, oauthauthorizationtransaction.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthAuthorizationTransaction fields.
func (_m *OAuthAuthorizationTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthauthorizationtransaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthauthorizationtransaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthauthorizationtransaction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthauthorizationtransaction.FieldTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_id", values[i])
			} else if value.Valid {
				_m.TransactionID = value.String
			}
		case oauthauthorizationtransaction.FieldRedirectURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uri", values[i])
			} else if value.Valid {
				_m.RedirectURI = value.String
			}
		case oauthauthorizationtransaction.FieldRequestedScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field requested_scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestedScopes); err != nil {
					return fmt.Errorf("unmarshal field requested_scopes: %w", err)
				}
			}
		case oauthauthorizationtransaction.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case oauthauthorizationtransaction.FieldCodeChallenge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_challenge", values[i])
			} else if value.Valid {
				_m.CodeChallenge = value.String
			}
		case oauthauthorizationtransaction.FieldCodeChallengeMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_challenge_method", values[i])
			} else if value.Valid {
				_m.CodeChallengeMethod = value.String
			}
		case oauthauthorizationtransaction.FieldBrowserSessionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field browser_session_hash", values[i])
			} else if value.Valid {
				_m.BrowserSessionHash = value.String
			}
		case oauthauthorizationtransaction.FieldCsrfTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field csrf_token_hash", values[i])
			} else if value.Valid {
				_m.CsrfTokenHash = value.String
			}
		case oauthauthorizationtransaction.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case oauthauthorizationtransaction.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case oauthauthorizationtransaction.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oauthauthorizationtransaction.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case oauthauthorizationtransaction.FieldClientID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthAuthorizationTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthAuthorizationTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OAuthAuthorizationTransaction entity.
func (_m *OAuthAuthorizationTransaction) QueryUser() *UserQuery {
	return NewOAuthAuthorizationTransactionClient(_m.config).QueryUser(_m)
}

// QueryClient queries the "client" edge of the OAuthAuthorizationTransaction entity.
func (_m *OAuthAuthorizationTransaction) QueryClient() *OAuthClientQuery {
	return NewOAuthAuthorizationTransactionClient(_m.config).QueryClient(_m)
}

// Update returns a builder for updating this OAuthAuthorizationTransaction.
// Note that you need to call OAuthAuthorizationTransaction.Unwrap() before calling this method if this OAuthAuthorizationTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthAuthorizationTransaction) Update() *OAuthAuthorizationTransactionUpdateOne {
	return NewOAuthAuthorizationTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthAuthorizationTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthAuthorizationTransaction) Unwrap() *OAuthAuthorizationTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthAuthorizationTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthAuthorizationTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthAuthorizationTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("transaction_id=")
	builder.WriteString(_m.TransactionID)
	builder.WriteString(", ")
	builder.WriteString("redirect_uri=")
	builder.WriteString(_m.RedirectURI)
	builder.WriteString(", ")
	builder.WriteString("requested_scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedScopes))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("code_challenge=")
	builder.WriteString(_m.CodeChallenge)
	builder.WriteString(", ")
	builder.WriteString("code_challenge_method=")
	builder.WriteString(_m.CodeChallengeMethod)
	builder.WriteString(", ")
	builder.WriteString("browser_session_hash=")
	builder.WriteString(_m.BrowserSessionHash)
	builder.WriteString(", ")
	builder.WriteString("csrf_token_hash=")
	builder.WriteString(_m.CsrfTokenHash)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthAuthorizationTransactions is a parsable slice of OAuthAuthorizationTransaction.
type OAuthAuthorizationTransactions []*OAuthAuthorizationTransaction
