// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthaccesstoken"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// OAuthAccessTokenUpdate is the builder for updating OAuthAccessToken entities.
type OAuthAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthAccessTokenMutation
}

// Where appends a list predicates to the OAuthAccessTokenUpdate builder.
func (_u *OAuthAccessTokenUpdate) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthAccessTokenUpdate) SetUpdatedAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthAccessTokenUpdate) SetTokenHash(v string) *OAuthAccessTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableTokenHash(v *string) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetHashKeyVersion sets the "hash_key_version" field.
func (_u *OAuthAccessTokenUpdate) SetHashKeyVersion(v int) *OAuthAccessTokenUpdate {
	_u.mutation.ResetHashKeyVersion()
	_u.mutation.SetHashKeyVersion(v)
	return _u
}

// SetNillableHashKeyVersion sets the "hash_key_version" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableHashKeyVersion(v *int) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetHashKeyVersion(*v)
	}
	return _u
}

// AddHashKeyVersion adds value to the "hash_key_version" field.
func (_u *OAuthAccessTokenUpdate) AddHashKeyVersion(v int) *OAuthAccessTokenUpdate {
	_u.mutation.AddHashKeyVersion(v)
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *OAuthAccessTokenUpdate) SetFamilyID(v uuid.UUID) *OAuthAccessTokenUpdate {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableFamilyID(v *uuid.UUID) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAccessTokenUpdate) SetScopes(v []string) *OAuthAccessTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAccessTokenUpdate) AppendScopes(v []string) *OAuthAccessTokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *OAuthAccessTokenUpdate) SetIssuedAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableIssuedAt(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAccessTokenUpdate) SetExpiresAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableExpiresAt(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthAccessTokenUpdate) SetRevokedAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableRevokedAt(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthAccessTokenUpdate) ClearRevokedAt() *OAuthAccessTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *OAuthAccessTokenUpdate) SetLastUsedAt(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableLastUsedAt(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *OAuthAccessTokenUpdate) ClearLastUsedAt() *OAuthAccessTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAccessTokenUpdate) SetUserID(v int64) *OAuthAccessTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableUserID(v *int64) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAccessTokenUpdate) SetClientID(v int64) *OAuthAccessTokenUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableClientID(v *int64) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthAccessTokenUpdate) SetUser(v *User) *OAuthAccessTokenUpdate {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthAccessTokenUpdate) SetClient(v *OAuthClient) *OAuthAccessTokenUpdate {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_u *OAuthAccessTokenUpdate) Mutation() *OAuthAccessTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthAccessTokenUpdate) ClearUser() *OAuthAccessTokenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthAccessTokenUpdate) ClearClient() *OAuthAccessTokenUpdate {
	_u.mutation.ClearClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthAccessTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthaccesstoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAccessTokenUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthaccesstoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAccessToken.token_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthAccessToken.user"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthAccessToken.client"`)
	}
	return nil
}

func (_u *OAuthAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthaccesstoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashKeyVersion(); ok {
		_spec.SetField(oauthaccesstoken.FieldHashKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHashKeyVersion(); ok {
		_spec.AddField(oauthaccesstoken.FieldHashKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(oauthaccesstoken.FieldFamilyID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthaccesstoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.UserTable,
			Columns: []string{oauthaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.UserTable,
			Columns: []string{oauthaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.ClientTable,
			Columns: []string{oauthaccesstoken.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.ClientTable,
			Columns: []string{oauthaccesstoken.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAccessTokenUpdateOne is the builder for updating a single OAuthAccessToken entity.
type OAuthAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthAccessTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetUpdatedAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthAccessTokenUpdateOne) SetTokenHash(v string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableTokenHash(v *string) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetHashKeyVersion sets the "hash_key_version" field.
func (_u *OAuthAccessTokenUpdateOne) SetHashKeyVersion(v int) *OAuthAccessTokenUpdateOne {
	_u.mutation.ResetHashKeyVersion()
	_u.mutation.SetHashKeyVersion(v)
	return _u
}

// SetNillableHashKeyVersion sets the "hash_key_version" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableHashKeyVersion(v *int) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetHashKeyVersion(*v)
	}
	return _u
}

// AddHashKeyVersion adds value to the "hash_key_version" field.
func (_u *OAuthAccessTokenUpdateOne) AddHashKeyVersion(v int) *OAuthAccessTokenUpdateOne {
	_u.mutation.AddHashKeyVersion(v)
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *OAuthAccessTokenUpdateOne) SetFamilyID(v uuid.UUID) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableFamilyID(v *uuid.UUID) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAccessTokenUpdateOne) SetScopes(v []string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAccessTokenUpdateOne) AppendScopes(v []string) *OAuthAccessTokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetIssuedAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableIssuedAt(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetExpiresAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetRevokedAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthAccessTokenUpdateOne) ClearRevokedAt() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *OAuthAccessTokenUpdateOne) SetLastUsedAt(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *OAuthAccessTokenUpdateOne) ClearLastUsedAt() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAccessTokenUpdateOne) SetUserID(v int64) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableUserID(v *int64) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAccessTokenUpdateOne) SetClientID(v int64) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableClientID(v *int64) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthAccessTokenUpdateOne) SetUser(v *User) *OAuthAccessTokenUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthAccessTokenUpdateOne) SetClient(v *OAuthClient) *OAuthAccessTokenUpdateOne {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_u *OAuthAccessTokenUpdateOne) Mutation() *OAuthAccessTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthAccessTokenUpdateOne) ClearUser() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthAccessTokenUpdateOne) ClearClient() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// Where appends a list predicates to the OAuthAccessTokenUpdate builder.
func (_u *OAuthAccessTokenUpdateOne) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAccessTokenUpdateOne) Select(field string, fields ...string) *OAuthAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAccessToken entity.
func (_u *OAuthAccessTokenUpdateOne) Save(ctx context.Context) (*OAuthAccessToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdateOne) SaveX(ctx context.Context) *OAuthAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthAccessTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthaccesstoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAccessTokenUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthaccesstoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAccessToken.token_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthAccessToken.user"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthAccessToken.client"`)
	}
	return nil
}

func (_u *OAuthAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAccessToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccesstoken.FieldID)
		for _, f := range fields {
			if !oauthaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthaccesstoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashKeyVersion(); ok {
		_spec.SetField(oauthaccesstoken.FieldHashKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHashKeyVersion(); ok {
		_spec.AddField(oauthaccesstoken.FieldHashKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(oauthaccesstoken.FieldFamilyID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthaccesstoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(oauthaccesstoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(oauthaccesstoken.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.UserTable,
			Columns: []string{oauthaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.UserTable,
			Columns: []string{oauthaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.ClientTable,
			Columns: []string{oauthaccesstoken.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthaccesstoken.ClientTable,
			Columns: []string{oauthaccesstoken.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
