// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthrefreshtoken"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// OAuthRefreshToken is the model entity for the OAuthRefreshToken schema.
type OAuthRefreshToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// HashKeyVersion holds the value of the "hash_key_version" field.
	HashKeyVersion int `json:"hash_key_version,omitempty"`
	// FamilyID holds the value of the "family_id" field.
	FamilyID uuid.UUID `json:"family_id,omitempty"`
	// Prior token in the rotation chain; null for the family root.
	ParentTokenID *int64 `json:"parent_token_id,omitempty"`
	// Token that superseded this one during rotation.
	ReplacedByTokenID *int64 `json:"replaced_by_token_id,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt time.Time `json:"issued_at,omitempty"`
	// Absolute validity deadline.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Idle validity deadline; null means no idle limit.
	IdleExpiresAt *time.Time `json:"idle_expires_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Internal FK to oauth_clients.id.
	ClientID int64 `json:"client_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthRefreshTokenQuery when eager-loading is set.
	Edges        OAuthRefreshTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthRefreshTokenEdges holds the relations/edges for other nodes in the graph.
type OAuthRefreshTokenEdges struct {
	// ChildTokens holds the value of the child_tokens edge.
	ChildTokens []*OAuthRefreshToken `json:"child_tokens,omitempty"`
	// ReplacedTokens holds the value of the replaced_tokens edge.
	ReplacedTokens []*OAuthRefreshToken `json:"replaced_tokens,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Client holds the value of the client edge.
	Client *OAuthClient `json:"client,omitempty"`
	// ParentToken holds the value of the parent_token edge.
	ParentToken *OAuthRefreshToken `json:"parent_token,omitempty"`
	// ReplacedByToken holds the value of the replaced_by_token edge.
	ReplacedByToken *OAuthRefreshToken `json:"replaced_by_token,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// ChildTokensOrErr returns the ChildTokens value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthRefreshTokenEdges) ChildTokensOrErr() ([]*OAuthRefreshToken, error) {
	if e.loadedTypes[0] {
		return e.ChildTokens, nil
	}
	return nil, &NotLoadedError{edge: "child_tokens"}
}

// ReplacedTokensOrErr returns the ReplacedTokens value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthRefreshTokenEdges) ReplacedTokensOrErr() ([]*OAuthRefreshToken, error) {
	if e.loadedTypes[1] {
		return e.ReplacedTokens, nil
	}
	return nil, &NotLoadedError{edge: "replaced_tokens"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthRefreshTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthRefreshTokenEdges) ClientOrErr() (*OAuthClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: oauthclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// ParentTokenOrErr returns the ParentToken value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthRefreshTokenEdges) ParentTokenOrErr() (*OAuthRefreshToken, error) {
	if e.ParentToken != nil {
		return e.ParentToken, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: oauthrefreshtoken.Label}
	}
	return nil, &NotLoadedError{edge: "parent_token"}
}

// ReplacedByTokenOrErr returns the ReplacedByToken value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthRefreshTokenEdges) ReplacedByTokenOrErr() (*OAuthRefreshToken, error) {
	if e.ReplacedByToken != nil {
		return e.ReplacedByToken, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: oauthrefreshtoken.Label}
	}
	return nil, &NotLoadedError{edge: "replaced_by_token"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthRefreshToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthrefreshtoken.FieldScopes:
			values[i] = new([]byte)
		case oauthrefreshtoken.FieldID, oauthrefreshtoken.FieldHashKeyVersion, oauthrefreshtoken.FieldParentTokenID, oauthrefreshtoken.FieldReplacedByTokenID, oauthrefreshtoken.FieldUserID, oauthrefreshtoken.FieldClientID:
			values[i] = new(sql.NullInt64)
		case oauthrefreshtoken.FieldTokenHash:
			values[i] = new(sql.NullString)
		case oauthrefreshtoken.FieldCreatedAt, oauthrefreshtoken.FieldUpdatedAt, oauthrefreshtoken.FieldIssuedAt, oauthrefreshtoken.FieldExpiresAt, oauthrefreshtoken.FieldIdleExpiresAt, oauthrefreshtoken.FieldLastUsedAt, oauthrefreshtoken.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case oauthrefreshtoken.FieldFamilyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthRefreshToken fields.
func (_m *OAuthRefreshToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthrefreshtoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthrefreshtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthrefreshtoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthrefreshtoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case oauthrefreshtoken.FieldHashKeyVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hash_key_version", values[i])
			} else if value.Valid {
				_m.HashKeyVersion = int(value.Int64)
			}
		case oauthrefreshtoken.FieldFamilyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field family_id", values[i])
			} else if value != nil {
				_m.FamilyID = *value
			}
		case oauthrefreshtoken.FieldParentTokenID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_token_id", values[i])
			} else if value.Valid {
				_m.ParentTokenID = new(int64)
				*_m.ParentTokenID = value.Int64
			}
		case oauthrefreshtoken.FieldReplacedByTokenID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field replaced_by_token_id", values[i])
			} else if value.Valid {
				_m.ReplacedByTokenID = new(int64)
				*_m.ReplacedByTokenID = value.Int64
			}
		case oauthrefreshtoken.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case oauthrefreshtoken.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = value.Time
			}
		case oauthrefreshtoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oauthrefreshtoken.FieldIdleExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field idle_expires_at", values[i])
			} else if value.Valid {
				_m.IdleExpiresAt = new(time.Time)
				*_m.IdleExpiresAt = value.Time
			}
		case oauthrefreshtoken.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case oauthrefreshtoken.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case oauthrefreshtoken.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case oauthrefreshtoken.FieldClientID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthRefreshToken.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthRefreshToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChildTokens queries the "child_tokens" edge of the OAuthRefreshToken entity.
func (_m *OAuthRefreshToken) QueryChildTokens() *OAuthRefreshTokenQuery {
	return NewOAuthRefreshTokenClient(_m.config).QueryChildTokens(_m)
}

// QueryReplacedTokens queries the "replaced_tokens" edge of the OAuthRefreshToken entity.
func (_m *OAuthRefreshToken) QueryReplacedTokens() *OAuthRefreshTokenQuery {
	return NewOAuthRefreshTokenClient(_m.config).QueryReplacedTokens(_m)
}

// QueryUser queries the "user" edge of the OAuthRefreshToken entity.
func (_m *OAuthRefreshToken) QueryUser() *UserQuery {
	return NewOAuthRefreshTokenClient(_m.config).QueryUser(_m)
}

// QueryClient queries the "client" edge of the OAuthRefreshToken entity.
func (_m *OAuthRefreshToken) QueryClient() *OAuthClientQuery {
	return NewOAuthRefreshTokenClient(_m.config).QueryClient(_m)
}

// QueryParentToken queries the "parent_token" edge of the OAuthRefreshToken entity.
func (_m *OAuthRefreshToken) QueryParentToken() *OAuthRefreshTokenQuery {
	return NewOAuthRefreshTokenClient(_m.config).QueryParentToken(_m)
}

// QueryReplacedByToken queries the "replaced_by_token" edge of the OAuthRefreshToken entity.
func (_m *OAuthRefreshToken) QueryReplacedByToken() *OAuthRefreshTokenQuery {
	return NewOAuthRefreshTokenClient(_m.config).QueryReplacedByToken(_m)
}

// Update returns a builder for updating this OAuthRefreshToken.
// Note that you need to call OAuthRefreshToken.Unwrap() before calling this method if this OAuthRefreshToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthRefreshToken) Update() *OAuthRefreshTokenUpdateOne {
	return NewOAuthRefreshTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthRefreshToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthRefreshToken) Unwrap() *OAuthRefreshToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthRefreshToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthRefreshToken) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthRefreshToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("hash_key_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.HashKeyVersion))
	builder.WriteString(", ")
	builder.WriteString("family_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FamilyID))
	builder.WriteString(", ")
	if v := _m.ParentTokenID; v != nil {
		builder.WriteString("parent_token_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReplacedByTokenID; v != nil {
		builder.WriteString("replaced_by_token_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("issued_at=")
	builder.WriteString(_m.IssuedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.IdleExpiresAt; v != nil {
		builder.WriteString("idle_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthRefreshTokens is a parsable slice of OAuthRefreshToken.
type OAuthRefreshTokens []*OAuthRefreshToken
