// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationtransaction"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthAuthorizationTransactionUpdate is the builder for updating OAuthAuthorizationTransaction entities.
type OAuthAuthorizationTransactionUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthAuthorizationTransactionMutation
}

// Where appends a list predicates to the OAuthAuthorizationTransactionUpdate builder.
func (_u *OAuthAuthorizationTransactionUpdate) Where(ps ...predicate.OAuthAuthorizationTransaction) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetUpdatedAt(v time.Time) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetTransactionID(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableTransactionID(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetRedirectURI(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableRedirectURI(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetRequestedScopes sets the "requested_scopes" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetRequestedScopes(v []string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetRequestedScopes(v)
	return _u
}

// AppendRequestedScopes appends value to the "requested_scopes" field.
func (_u *OAuthAuthorizationTransactionUpdate) AppendRequestedScopes(v []string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.AppendRequestedScopes(v)
	return _u
}

// SetState sets the "state" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetState(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableState(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetCodeChallenge(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableCodeChallenge(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetCodeChallengeMethod(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetBrowserSessionHash sets the "browser_session_hash" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetBrowserSessionHash(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetBrowserSessionHash(v)
	return _u
}

// SetNillableBrowserSessionHash sets the "browser_session_hash" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableBrowserSessionHash(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetBrowserSessionHash(*v)
	}
	return _u
}

// SetCsrfTokenHash sets the "csrf_token_hash" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetCsrfTokenHash(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetCsrfTokenHash(v)
	return _u
}

// SetNillableCsrfTokenHash sets the "csrf_token_hash" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableCsrfTokenHash(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetCsrfTokenHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetUserID(v int64) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableUserID(v *int64) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthAuthorizationTransactionUpdate) ClearUserID() *OAuthAuthorizationTransactionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetStatus(v string) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableStatus(v *string) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetExpiresAt(v time.Time) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetConsumedAt(v time.Time) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableConsumedAt(v *time.Time) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *OAuthAuthorizationTransactionUpdate) ClearConsumedAt() *OAuthAuthorizationTransactionUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationTransactionUpdate) SetClientID(v int64) *OAuthAuthorizationTransactionUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdate) SetNillableClientID(v *int64) *OAuthAuthorizationTransactionUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthAuthorizationTransactionUpdate) SetUser(v *User) *OAuthAuthorizationTransactionUpdate {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthAuthorizationTransactionUpdate) SetClient(v *OAuthClient) *OAuthAuthorizationTransactionUpdate {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthAuthorizationTransactionMutation object of the builder.
func (_u *OAuthAuthorizationTransactionUpdate) Mutation() *OAuthAuthorizationTransactionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthAuthorizationTransactionUpdate) ClearUser() *OAuthAuthorizationTransactionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthAuthorizationTransactionUpdate) ClearClient() *OAuthAuthorizationTransactionUpdate {
	_u.mutation.ClearClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAuthorizationTransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAuthorizationTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthAuthorizationTransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthauthorizationtransaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationTransactionUpdate) check() error {
	if v, ok := _u.mutation.TransactionID(); ok {
		if err := oauthauthorizationtransaction.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthauthorizationtransaction.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := oauthauthorizationtransaction.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthauthorizationtransaction.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallengeMethod(); ok {
		if err := oauthauthorizationtransaction.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrowserSessionHash(); ok {
		if err := oauthauthorizationtransaction.BrowserSessionHashValidator(v); err != nil {
			return &ValidationError{Name: "browser_session_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.browser_session_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CsrfTokenHash(); ok {
		if err := oauthauthorizationtransaction.CsrfTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "csrf_token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.csrf_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthauthorizationtransaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.status": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthAuthorizationTransaction.client"`)
	}
	return nil
}

func (_u *OAuthAuthorizationTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationtransaction.Table, oauthauthorizationtransaction.Columns, sqlgraph.NewFieldSpec(oauthauthorizationtransaction.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TransactionID(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldTransactionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedScopes(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldRequestedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorizationtransaction.FieldRequestedScopes, value)
		})
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrowserSessionHash(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldBrowserSessionHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CsrfTokenHash(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldCsrfTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(oauthauthorizationtransaction.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.UserTable,
			Columns: []string{oauthauthorizationtransaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.UserTable,
			Columns: []string{oauthauthorizationtransaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.ClientTable,
			Columns: []string{oauthauthorizationtransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.ClientTable,
			Columns: []string{oauthauthorizationtransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationtransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAuthorizationTransactionUpdateOne is the builder for updating a single OAuthAuthorizationTransaction entity.
type OAuthAuthorizationTransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthAuthorizationTransactionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetUpdatedAt(v time.Time) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetTransactionID(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableTransactionID(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetRedirectURI(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableRedirectURI(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetRequestedScopes sets the "requested_scopes" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetRequestedScopes(v []string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetRequestedScopes(v)
	return _u
}

// AppendRequestedScopes appends value to the "requested_scopes" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) AppendRequestedScopes(v []string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.AppendRequestedScopes(v)
	return _u
}

// SetState sets the "state" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetState(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableState(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetCodeChallenge(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableCodeChallenge(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetCodeChallengeMethod(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetBrowserSessionHash sets the "browser_session_hash" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetBrowserSessionHash(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetBrowserSessionHash(v)
	return _u
}

// SetNillableBrowserSessionHash sets the "browser_session_hash" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableBrowserSessionHash(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetBrowserSessionHash(*v)
	}
	return _u
}

// SetCsrfTokenHash sets the "csrf_token_hash" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetCsrfTokenHash(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetCsrfTokenHash(v)
	return _u
}

// SetNillableCsrfTokenHash sets the "csrf_token_hash" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableCsrfTokenHash(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetCsrfTokenHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetUserID(v int64) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableUserID(v *int64) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) ClearUserID() *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetStatus(v string) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableStatus(v *string) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetExpiresAt(v time.Time) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetConsumedAt(v time.Time) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableConsumedAt(v *time.Time) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) ClearConsumedAt() *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetClientID(v int64) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetNillableClientID(v *int64) *OAuthAuthorizationTransactionUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetUser(v *User) *OAuthAuthorizationTransactionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthAuthorizationTransactionUpdateOne) SetClient(v *OAuthClient) *OAuthAuthorizationTransactionUpdateOne {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthAuthorizationTransactionMutation object of the builder.
func (_u *OAuthAuthorizationTransactionUpdateOne) Mutation() *OAuthAuthorizationTransactionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthAuthorizationTransactionUpdateOne) ClearUser() *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthAuthorizationTransactionUpdateOne) ClearClient() *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// Where appends a list predicates to the OAuthAuthorizationTransactionUpdate builder.
func (_u *OAuthAuthorizationTransactionUpdateOne) Where(ps ...predicate.OAuthAuthorizationTransaction) *OAuthAuthorizationTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAuthorizationTransactionUpdateOne) Select(field string, fields ...string) *OAuthAuthorizationTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAuthorizationTransaction entity.
func (_u *OAuthAuthorizationTransactionUpdateOne) Save(ctx context.Context) (*OAuthAuthorizationTransaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationTransactionUpdateOne) SaveX(ctx context.Context) *OAuthAuthorizationTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAuthorizationTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthAuthorizationTransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthauthorizationtransaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationTransactionUpdateOne) check() error {
	if v, ok := _u.mutation.TransactionID(); ok {
		if err := oauthauthorizationtransaction.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthauthorizationtransaction.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := oauthauthorizationtransaction.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthauthorizationtransaction.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallengeMethod(); ok {
		if err := oauthauthorizationtransaction.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrowserSessionHash(); ok {
		if err := oauthauthorizationtransaction.BrowserSessionHashValidator(v); err != nil {
			return &ValidationError{Name: "browser_session_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.browser_session_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CsrfTokenHash(); ok {
		if err := oauthauthorizationtransaction.CsrfTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "csrf_token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.csrf_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthauthorizationtransaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationTransaction.status": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthAuthorizationTransaction.client"`)
	}
	return nil
}

func (_u *OAuthAuthorizationTransactionUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAuthorizationTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationtransaction.Table, oauthauthorizationtransaction.Columns, sqlgraph.NewFieldSpec(oauthauthorizationtransaction.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthAuthorizationTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthauthorizationtransaction.FieldID)
		for _, f := range fields {
			if !oauthauthorizationtransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthauthorizationtransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TransactionID(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldTransactionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedScopes(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldRequestedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorizationtransaction.FieldRequestedScopes, value)
		})
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrowserSessionHash(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldBrowserSessionHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CsrfTokenHash(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldCsrfTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthauthorizationtransaction.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(oauthauthorizationtransaction.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.UserTable,
			Columns: []string{oauthauthorizationtransaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.UserTable,
			Columns: []string{oauthauthorizationtransaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.ClientTable,
			Columns: []string{oauthauthorizationtransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationtransaction.ClientTable,
			Columns: []string{oauthauthorizationtransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthAuthorizationTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationtransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
