// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthrefreshtoken"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthRefreshTokenQuery is the builder for querying OAuthRefreshToken entities.
type OAuthRefreshTokenQuery struct {
	config
	ctx                 *QueryContext
	order               []oauthrefreshtoken.OrderOption
	inters              []Interceptor
	predicates          []predicate.OAuthRefreshToken
	withChildTokens     *OAuthRefreshTokenQuery
	withReplacedTokens  *OAuthRefreshTokenQuery
	withUser            *UserQuery
	withClient          *OAuthClientQuery
	withParentToken     *OAuthRefreshTokenQuery
	withReplacedByToken *OAuthRefreshTokenQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OAuthRefreshTokenQuery builder.
func (_q *OAuthRefreshTokenQuery) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OAuthRefreshTokenQuery) Limit(limit int) *OAuthRefreshTokenQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OAuthRefreshTokenQuery) Offset(offset int) *OAuthRefreshTokenQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OAuthRefreshTokenQuery) Unique(unique bool) *OAuthRefreshTokenQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OAuthRefreshTokenQuery) Order(o ...oauthrefreshtoken.OrderOption) *OAuthRefreshTokenQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChildTokens chains the current query on the "child_tokens" edge.
func (_q *OAuthRefreshTokenQuery) QueryChildTokens() *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID, selector),
			sqlgraph.To(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthrefreshtoken.ChildTokensTable, oauthrefreshtoken.ChildTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReplacedTokens chains the current query on the "replaced_tokens" edge.
func (_q *OAuthRefreshTokenQuery) QueryReplacedTokens() *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID, selector),
			sqlgraph.To(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthrefreshtoken.ReplacedTokensTable, oauthrefreshtoken.ReplacedTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *OAuthRefreshTokenQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oauthrefreshtoken.UserTable, oauthrefreshtoken.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClient chains the current query on the "client" edge.
func (_q *OAuthRefreshTokenQuery) QueryClient() *OAuthClientQuery {
	query := (&OAuthClientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID, selector),
			sqlgraph.To(oauthclient.Table, oauthclient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oauthrefreshtoken.ClientTable, oauthrefreshtoken.ClientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParentToken chains the current query on the "parent_token" edge.
func (_q *OAuthRefreshTokenQuery) QueryParentToken() *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID, selector),
			sqlgraph.To(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oauthrefreshtoken.ParentTokenTable, oauthrefreshtoken.ParentTokenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReplacedByToken chains the current query on the "replaced_by_token" edge.
func (_q *OAuthRefreshTokenQuery) QueryReplacedByToken() *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID, selector),
			sqlgraph.To(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oauthrefreshtoken.ReplacedByTokenTable, oauthrefreshtoken.ReplacedByTokenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OAuthRefreshToken entity from the query.
// Returns a *NotFoundError when no OAuthRefreshToken was found.
func (_q *OAuthRefreshTokenQuery) First(ctx context.Context) (*OAuthRefreshToken, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oauthrefreshtoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) FirstX(ctx context.Context) *OAuthRefreshToken {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OAuthRefreshToken ID from the query.
// Returns a *NotFoundError when no OAuthRefreshToken ID was found.
func (_q *OAuthRefreshTokenQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oauthrefreshtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OAuthRefreshToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OAuthRefreshToken entity is found.
// Returns a *NotFoundError when no OAuthRefreshToken entities are found.
func (_q *OAuthRefreshTokenQuery) Only(ctx context.Context) (*OAuthRefreshToken, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oauthrefreshtoken.Label}
	default:
		return nil, &NotSingularError{oauthrefreshtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) OnlyX(ctx context.Context) *OAuthRefreshToken {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OAuthRefreshToken ID in the query.
// Returns a *NotSingularError when more than one OAuthRefreshToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OAuthRefreshTokenQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oauthrefreshtoken.Label}
	default:
		err = &NotSingularError{oauthrefreshtoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OAuthRefreshTokens.
func (_q *OAuthRefreshTokenQuery) All(ctx context.Context) ([]*OAuthRefreshToken, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OAuthRefreshToken, *OAuthRefreshTokenQuery]()
	return withInterceptors[[]*OAuthRefreshToken](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) AllX(ctx context.Context) []*OAuthRefreshToken {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OAuthRefreshToken IDs.
func (_q *OAuthRefreshTokenQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(oauthrefreshtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OAuthRefreshTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OAuthRefreshTokenQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OAuthRefreshTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OAuthRefreshTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OAuthRefreshTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OAuthRefreshTokenQuery) Clone() *OAuthRefreshTokenQuery {
	if _q == nil {
		return nil
	}
	return &OAuthRefreshTokenQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]oauthrefreshtoken.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.OAuthRefreshToken{}, _q.predicates...),
		withChildTokens:     _q.withChildTokens.Clone(),
		withReplacedTokens:  _q.withReplacedTokens.Clone(),
		withUser:            _q.withUser.Clone(),
		withClient:          _q.withClient.Clone(),
		withParentToken:     _q.withParentToken.Clone(),
		withReplacedByToken: _q.withReplacedByToken.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChildTokens tells the query-builder to eager-load the nodes that are connected to
// the "child_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthRefreshTokenQuery) WithChildTokens(opts ...func(*OAuthRefreshTokenQuery)) *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildTokens = query
	return _q
}

// WithReplacedTokens tells the query-builder to eager-load the nodes that are connected to
// the "replaced_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthRefreshTokenQuery) WithReplacedTokens(opts ...func(*OAuthRefreshTokenQuery)) *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReplacedTokens = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthRefreshTokenQuery) WithUser(opts ...func(*UserQuery)) *OAuthRefreshTokenQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithClient tells the query-builder to eager-load the nodes that are connected to
// the "client" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthRefreshTokenQuery) WithClient(opts ...func(*OAuthClientQuery)) *OAuthRefreshTokenQuery {
	query := (&OAuthClientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClient = query
	return _q
}

// WithParentToken tells the query-builder to eager-load the nodes that are connected to
// the "parent_token" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthRefreshTokenQuery) WithParentToken(opts ...func(*OAuthRefreshTokenQuery)) *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParentToken = query
	return _q
}

// WithReplacedByToken tells the query-builder to eager-load the nodes that are connected to
// the "replaced_by_token" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthRefreshTokenQuery) WithReplacedByToken(opts ...func(*OAuthRefreshTokenQuery)) *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReplacedByToken = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OAuthRefreshToken.Query().
//		GroupBy(oauthrefreshtoken.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OAuthRefreshTokenQuery) GroupBy(field string, fields ...string) *OAuthRefreshTokenGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OAuthRefreshTokenGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = oauthrefreshtoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OAuthRefreshToken.Query().
//		Select(oauthrefreshtoken.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OAuthRefreshTokenQuery) Select(fields ...string) *OAuthRefreshTokenSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OAuthRefreshTokenSelect{OAuthRefreshTokenQuery: _q}
	sbuild.label = oauthrefreshtoken.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OAuthRefreshTokenSelect configured with the given aggregations.
func (_q *OAuthRefreshTokenQuery) Aggregate(fns ...AggregateFunc) *OAuthRefreshTokenSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OAuthRefreshTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !oauthrefreshtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OAuthRefreshTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OAuthRefreshToken, error) {
	var (
		nodes       = []*OAuthRefreshToken{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withChildTokens != nil,
			_q.withReplacedTokens != nil,
			_q.withUser != nil,
			_q.withClient != nil,
			_q.withParentToken != nil,
			_q.withReplacedByToken != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OAuthRefreshToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OAuthRefreshToken{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChildTokens; query != nil {
		if err := _q.loadChildTokens(ctx, query, nodes,
			func(n *OAuthRefreshToken) { n.Edges.ChildTokens = []*OAuthRefreshToken{} },
			func(n *OAuthRefreshToken, e *OAuthRefreshToken) { n.Edges.ChildTokens = append(n.Edges.ChildTokens, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReplacedTokens; query != nil {
		if err := _q.loadReplacedTokens(ctx, query, nodes,
			func(n *OAuthRefreshToken) { n.Edges.ReplacedTokens = []*OAuthRefreshToken{} },
			func(n *OAuthRefreshToken, e *OAuthRefreshToken) {
				n.Edges.ReplacedTokens = append(n.Edges.ReplacedTokens, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *OAuthRefreshToken, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withClient; query != nil {
		if err := _q.loadClient(ctx, query, nodes, nil,
			func(n *OAuthRefreshToken, e *OAuthClient) { n.Edges.Client = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParentToken; query != nil {
		if err := _q.loadParentToken(ctx, query, nodes, nil,
			func(n *OAuthRefreshToken, e *OAuthRefreshToken) { n.Edges.ParentToken = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReplacedByToken; query != nil {
		if err := _q.loadReplacedByToken(ctx, query, nodes, nil,
			func(n *OAuthRefreshToken, e *OAuthRefreshToken) { n.Edges.ReplacedByToken = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OAuthRefreshTokenQuery) loadChildTokens(ctx context.Context, query *OAuthRefreshTokenQuery, nodes []*OAuthRefreshToken, init func(*OAuthRefreshToken), assign func(*OAuthRefreshToken, *OAuthRefreshToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthRefreshToken)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthrefreshtoken.FieldParentTokenID)
	}
	query.Where(predicate.OAuthRefreshToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthrefreshtoken.ChildTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentTokenID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_token_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_token_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthRefreshTokenQuery) loadReplacedTokens(ctx context.Context, query *OAuthRefreshTokenQuery, nodes []*OAuthRefreshToken, init func(*OAuthRefreshToken), assign func(*OAuthRefreshToken, *OAuthRefreshToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthRefreshToken)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthrefreshtoken.FieldReplacedByTokenID)
	}
	query.Where(predicate.OAuthRefreshToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthrefreshtoken.ReplacedTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ReplacedByTokenID
		if fk == nil {
			return fmt.Errorf(`foreign-key "replaced_by_token_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "replaced_by_token_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthRefreshTokenQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*OAuthRefreshToken, init func(*OAuthRefreshToken), assign func(*OAuthRefreshToken, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OAuthRefreshToken)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OAuthRefreshTokenQuery) loadClient(ctx context.Context, query *OAuthClientQuery, nodes []*OAuthRefreshToken, init func(*OAuthRefreshToken), assign func(*OAuthRefreshToken, *OAuthClient)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OAuthRefreshToken)
	for i := range nodes {
		fk := nodes[i].ClientID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(oauthclient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "client_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OAuthRefreshTokenQuery) loadParentToken(ctx context.Context, query *OAuthRefreshTokenQuery, nodes []*OAuthRefreshToken, init func(*OAuthRefreshToken), assign func(*OAuthRefreshToken, *OAuthRefreshToken)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OAuthRefreshToken)
	for i := range nodes {
		if nodes[i].ParentTokenID == nil {
			continue
		}
		fk := *nodes[i].ParentTokenID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(oauthrefreshtoken.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_token_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OAuthRefreshTokenQuery) loadReplacedByToken(ctx context.Context, query *OAuthRefreshTokenQuery, nodes []*OAuthRefreshToken, init func(*OAuthRefreshToken), assign func(*OAuthRefreshToken, *OAuthRefreshToken)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OAuthRefreshToken)
	for i := range nodes {
		if nodes[i].ReplacedByTokenID == nil {
			continue
		}
		fk := *nodes[i].ReplacedByTokenID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(oauthrefreshtoken.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "replaced_by_token_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *OAuthRefreshTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OAuthRefreshTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthrefreshtoken.FieldID)
		for i := range fields {
			if fields[i] != oauthrefreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(oauthrefreshtoken.FieldUserID)
		}
		if _q.withClient != nil {
			_spec.Node.AddColumnOnce(oauthrefreshtoken.FieldClientID)
		}
		if _q.withParentToken != nil {
			_spec.Node.AddColumnOnce(oauthrefreshtoken.FieldParentTokenID)
		}
		if _q.withReplacedByToken != nil {
			_spec.Node.AddColumnOnce(oauthrefreshtoken.FieldReplacedByTokenID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OAuthRefreshTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(oauthrefreshtoken.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = oauthrefreshtoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *OAuthRefreshTokenQuery) ForUpdate(opts ...sql.LockOption) *OAuthRefreshTokenQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *OAuthRefreshTokenQuery) ForShare(opts ...sql.LockOption) *OAuthRefreshTokenQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// OAuthRefreshTokenGroupBy is the group-by builder for OAuthRefreshToken entities.
type OAuthRefreshTokenGroupBy struct {
	selector
	build *OAuthRefreshTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OAuthRefreshTokenGroupBy) Aggregate(fns ...AggregateFunc) *OAuthRefreshTokenGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OAuthRefreshTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthRefreshTokenQuery, *OAuthRefreshTokenGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OAuthRefreshTokenGroupBy) sqlScan(ctx context.Context, root *OAuthRefreshTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OAuthRefreshTokenSelect is the builder for selecting fields of OAuthRefreshToken entities.
type OAuthRefreshTokenSelect struct {
	*OAuthRefreshTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OAuthRefreshTokenSelect) Aggregate(fns ...AggregateFunc) *OAuthRefreshTokenSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OAuthRefreshTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthRefreshTokenQuery, *OAuthRefreshTokenSelect](ctx, _s.OAuthRefreshTokenQuery, _s, _s.inters, v)
}

func (_s *OAuthRefreshTokenSelect) sqlScan(ctx context.Context, root *OAuthRefreshTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
