// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthaccesstoken"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationcode"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationtransaction"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthconsent"
	"github.com/Wei-Shaw/sub2api/ent/oauthmanagedapikey"
	"github.com/Wei-Shaw/sub2api/ent/oauthrefreshtoken"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthClientQuery is the builder for querying OAuthClient entities.
type OAuthClientQuery struct {
	config
	ctx                                *QueryContext
	order                              []oauthclient.OrderOption
	inters                             []Interceptor
	predicates                         []predicate.OAuthClient
	withOauthAuthorizationTransactions *OAuthAuthorizationTransactionQuery
	withOauthAuthorizationCodes        *OAuthAuthorizationCodeQuery
	withOauthConsents                  *OAuthConsentQuery
	withOauthAccessTokens              *OAuthAccessTokenQuery
	withOauthRefreshTokens             *OAuthRefreshTokenQuery
	withOauthManagedAPIKeys            *OAuthManagedAPIKeyQuery
	modifiers                          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OAuthClientQuery builder.
func (_q *OAuthClientQuery) Where(ps ...predicate.OAuthClient) *OAuthClientQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OAuthClientQuery) Limit(limit int) *OAuthClientQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OAuthClientQuery) Offset(offset int) *OAuthClientQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OAuthClientQuery) Unique(unique bool) *OAuthClientQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OAuthClientQuery) Order(o ...oauthclient.OrderOption) *OAuthClientQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOauthAuthorizationTransactions chains the current query on the "oauth_authorization_transactions" edge.
func (_q *OAuthClientQuery) QueryOauthAuthorizationTransactions() *OAuthAuthorizationTransactionQuery {
	query := (&OAuthAuthorizationTransactionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthclient.Table, oauthclient.FieldID, selector),
			sqlgraph.To(oauthauthorizationtransaction.Table, oauthauthorizationtransaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthclient.OauthAuthorizationTransactionsTable, oauthclient.OauthAuthorizationTransactionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOauthAuthorizationCodes chains the current query on the "oauth_authorization_codes" edge.
func (_q *OAuthClientQuery) QueryOauthAuthorizationCodes() *OAuthAuthorizationCodeQuery {
	query := (&OAuthAuthorizationCodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthclient.Table, oauthclient.FieldID, selector),
			sqlgraph.To(oauthauthorizationcode.Table, oauthauthorizationcode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthclient.OauthAuthorizationCodesTable, oauthclient.OauthAuthorizationCodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOauthConsents chains the current query on the "oauth_consents" edge.
func (_q *OAuthClientQuery) QueryOauthConsents() *OAuthConsentQuery {
	query := (&OAuthConsentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthclient.Table, oauthclient.FieldID, selector),
			sqlgraph.To(oauthconsent.Table, oauthconsent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthclient.OauthConsentsTable, oauthclient.OauthConsentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOauthAccessTokens chains the current query on the "oauth_access_tokens" edge.
func (_q *OAuthClientQuery) QueryOauthAccessTokens() *OAuthAccessTokenQuery {
	query := (&OAuthAccessTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthclient.Table, oauthclient.FieldID, selector),
			sqlgraph.To(oauthaccesstoken.Table, oauthaccesstoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthclient.OauthAccessTokensTable, oauthclient.OauthAccessTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOauthRefreshTokens chains the current query on the "oauth_refresh_tokens" edge.
func (_q *OAuthClientQuery) QueryOauthRefreshTokens() *OAuthRefreshTokenQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthclient.Table, oauthclient.FieldID, selector),
			sqlgraph.To(oauthrefreshtoken.Table, oauthrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthclient.OauthRefreshTokensTable, oauthclient.OauthRefreshTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOauthManagedAPIKeys chains the current query on the "oauth_managed_api_keys" edge.
func (_q *OAuthClientQuery) QueryOauthManagedAPIKeys() *OAuthManagedAPIKeyQuery {
	query := (&OAuthManagedAPIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthclient.Table, oauthclient.FieldID, selector),
			sqlgraph.To(oauthmanagedapikey.Table, oauthmanagedapikey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthclient.OauthManagedAPIKeysTable, oauthclient.OauthManagedAPIKeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OAuthClient entity from the query.
// Returns a *NotFoundError when no OAuthClient was found.
func (_q *OAuthClientQuery) First(ctx context.Context) (*OAuthClient, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oauthclient.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OAuthClientQuery) FirstX(ctx context.Context) *OAuthClient {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OAuthClient ID from the query.
// Returns a *NotFoundError when no OAuthClient ID was found.
func (_q *OAuthClientQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oauthclient.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OAuthClientQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OAuthClient entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OAuthClient entity is found.
// Returns a *NotFoundError when no OAuthClient entities are found.
func (_q *OAuthClientQuery) Only(ctx context.Context) (*OAuthClient, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oauthclient.Label}
	default:
		return nil, &NotSingularError{oauthclient.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OAuthClientQuery) OnlyX(ctx context.Context) *OAuthClient {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OAuthClient ID in the query.
// Returns a *NotSingularError when more than one OAuthClient ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OAuthClientQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oauthclient.Label}
	default:
		err = &NotSingularError{oauthclient.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OAuthClientQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OAuthClients.
func (_q *OAuthClientQuery) All(ctx context.Context) ([]*OAuthClient, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OAuthClient, *OAuthClientQuery]()
	return withInterceptors[[]*OAuthClient](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OAuthClientQuery) AllX(ctx context.Context) []*OAuthClient {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OAuthClient IDs.
func (_q *OAuthClientQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(oauthclient.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OAuthClientQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OAuthClientQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OAuthClientQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OAuthClientQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OAuthClientQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OAuthClientQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OAuthClientQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OAuthClientQuery) Clone() *OAuthClientQuery {
	if _q == nil {
		return nil
	}
	return &OAuthClientQuery{
		config:                             _q.config,
		ctx:                                _q.ctx.Clone(),
		order:                              append([]oauthclient.OrderOption{}, _q.order...),
		inters:                             append([]Interceptor{}, _q.inters...),
		predicates:                         append([]predicate.OAuthClient{}, _q.predicates...),
		withOauthAuthorizationTransactions: _q.withOauthAuthorizationTransactions.Clone(),
		withOauthAuthorizationCodes:        _q.withOauthAuthorizationCodes.Clone(),
		withOauthConsents:                  _q.withOauthConsents.Clone(),
		withOauthAccessTokens:              _q.withOauthAccessTokens.Clone(),
		withOauthRefreshTokens:             _q.withOauthRefreshTokens.Clone(),
		withOauthManagedAPIKeys:            _q.withOauthManagedAPIKeys.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOauthAuthorizationTransactions tells the query-builder to eager-load the nodes that are connected to
// the "oauth_authorization_transactions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthClientQuery) WithOauthAuthorizationTransactions(opts ...func(*OAuthAuthorizationTransactionQuery)) *OAuthClientQuery {
	query := (&OAuthAuthorizationTransactionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOauthAuthorizationTransactions = query
	return _q
}

// WithOauthAuthorizationCodes tells the query-builder to eager-load the nodes that are connected to
// the "oauth_authorization_codes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthClientQuery) WithOauthAuthorizationCodes(opts ...func(*OAuthAuthorizationCodeQuery)) *OAuthClientQuery {
	query := (&OAuthAuthorizationCodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOauthAuthorizationCodes = query
	return _q
}

// WithOauthConsents tells the query-builder to eager-load the nodes that are connected to
// the "oauth_consents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthClientQuery) WithOauthConsents(opts ...func(*OAuthConsentQuery)) *OAuthClientQuery {
	query := (&OAuthConsentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOauthConsents = query
	return _q
}

// WithOauthAccessTokens tells the query-builder to eager-load the nodes that are connected to
// the "oauth_access_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthClientQuery) WithOauthAccessTokens(opts ...func(*OAuthAccessTokenQuery)) *OAuthClientQuery {
	query := (&OAuthAccessTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOauthAccessTokens = query
	return _q
}

// WithOauthRefreshTokens tells the query-builder to eager-load the nodes that are connected to
// the "oauth_refresh_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthClientQuery) WithOauthRefreshTokens(opts ...func(*OAuthRefreshTokenQuery)) *OAuthClientQuery {
	query := (&OAuthRefreshTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOauthRefreshTokens = query
	return _q
}

// WithOauthManagedAPIKeys tells the query-builder to eager-load the nodes that are connected to
// the "oauth_managed_api_keys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthClientQuery) WithOauthManagedAPIKeys(opts ...func(*OAuthManagedAPIKeyQuery)) *OAuthClientQuery {
	query := (&OAuthManagedAPIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOauthManagedAPIKeys = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OAuthClient.Query().
//		GroupBy(oauthclient.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OAuthClientQuery) GroupBy(field string, fields ...string) *OAuthClientGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OAuthClientGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = oauthclient.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OAuthClient.Query().
//		Select(oauthclient.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OAuthClientQuery) Select(fields ...string) *OAuthClientSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OAuthClientSelect{OAuthClientQuery: _q}
	sbuild.label = oauthclient.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OAuthClientSelect configured with the given aggregations.
func (_q *OAuthClientQuery) Aggregate(fns ...AggregateFunc) *OAuthClientSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OAuthClientQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !oauthclient.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OAuthClientQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OAuthClient, error) {
	var (
		nodes       = []*OAuthClient{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withOauthAuthorizationTransactions != nil,
			_q.withOauthAuthorizationCodes != nil,
			_q.withOauthConsents != nil,
			_q.withOauthAccessTokens != nil,
			_q.withOauthRefreshTokens != nil,
			_q.withOauthManagedAPIKeys != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OAuthClient).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OAuthClient{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOauthAuthorizationTransactions; query != nil {
		if err := _q.loadOauthAuthorizationTransactions(ctx, query, nodes,
			func(n *OAuthClient) { n.Edges.OauthAuthorizationTransactions = []*OAuthAuthorizationTransaction{} },
			func(n *OAuthClient, e *OAuthAuthorizationTransaction) {
				n.Edges.OauthAuthorizationTransactions = append(n.Edges.OauthAuthorizationTransactions, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withOauthAuthorizationCodes; query != nil {
		if err := _q.loadOauthAuthorizationCodes(ctx, query, nodes,
			func(n *OAuthClient) { n.Edges.OauthAuthorizationCodes = []*OAuthAuthorizationCode{} },
			func(n *OAuthClient, e *OAuthAuthorizationCode) {
				n.Edges.OauthAuthorizationCodes = append(n.Edges.OauthAuthorizationCodes, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withOauthConsents; query != nil {
		if err := _q.loadOauthConsents(ctx, query, nodes,
			func(n *OAuthClient) { n.Edges.OauthConsents = []*OAuthConsent{} },
			func(n *OAuthClient, e *OAuthConsent) { n.Edges.OauthConsents = append(n.Edges.OauthConsents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOauthAccessTokens; query != nil {
		if err := _q.loadOauthAccessTokens(ctx, query, nodes,
			func(n *OAuthClient) { n.Edges.OauthAccessTokens = []*OAuthAccessToken{} },
			func(n *OAuthClient, e *OAuthAccessToken) {
				n.Edges.OauthAccessTokens = append(n.Edges.OauthAccessTokens, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withOauthRefreshTokens; query != nil {
		if err := _q.loadOauthRefreshTokens(ctx, query, nodes,
			func(n *OAuthClient) { n.Edges.OauthRefreshTokens = []*OAuthRefreshToken{} },
			func(n *OAuthClient, e *OAuthRefreshToken) {
				n.Edges.OauthRefreshTokens = append(n.Edges.OauthRefreshTokens, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withOauthManagedAPIKeys; query != nil {
		if err := _q.loadOauthManagedAPIKeys(ctx, query, nodes,
			func(n *OAuthClient) { n.Edges.OauthManagedAPIKeys = []*OAuthManagedAPIKey{} },
			func(n *OAuthClient, e *OAuthManagedAPIKey) {
				n.Edges.OauthManagedAPIKeys = append(n.Edges.OauthManagedAPIKeys, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OAuthClientQuery) loadOauthAuthorizationTransactions(ctx context.Context, query *OAuthAuthorizationTransactionQuery, nodes []*OAuthClient, init func(*OAuthClient), assign func(*OAuthClient, *OAuthAuthorizationTransaction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthauthorizationtransaction.FieldClientID)
	}
	query.Where(predicate.OAuthAuthorizationTransaction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthclient.OauthAuthorizationTransactionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthClientQuery) loadOauthAuthorizationCodes(ctx context.Context, query *OAuthAuthorizationCodeQuery, nodes []*OAuthClient, init func(*OAuthClient), assign func(*OAuthClient, *OAuthAuthorizationCode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthauthorizationcode.FieldClientID)
	}
	query.Where(predicate.OAuthAuthorizationCode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthclient.OauthAuthorizationCodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthClientQuery) loadOauthConsents(ctx context.Context, query *OAuthConsentQuery, nodes []*OAuthClient, init func(*OAuthClient), assign func(*OAuthClient, *OAuthConsent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthconsent.FieldClientID)
	}
	query.Where(predicate.OAuthConsent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthclient.OauthConsentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthClientQuery) loadOauthAccessTokens(ctx context.Context, query *OAuthAccessTokenQuery, nodes []*OAuthClient, init func(*OAuthClient), assign func(*OAuthClient, *OAuthAccessToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthaccesstoken.FieldClientID)
	}
	query.Where(predicate.OAuthAccessToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthclient.OauthAccessTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthClientQuery) loadOauthRefreshTokens(ctx context.Context, query *OAuthRefreshTokenQuery, nodes []*OAuthClient, init func(*OAuthClient), assign func(*OAuthClient, *OAuthRefreshToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthrefreshtoken.FieldClientID)
	}
	query.Where(predicate.OAuthRefreshToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthclient.OauthRefreshTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthClientQuery) loadOauthManagedAPIKeys(ctx context.Context, query *OAuthManagedAPIKeyQuery, nodes []*OAuthClient, init func(*OAuthClient), assign func(*OAuthClient, *OAuthManagedAPIKey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthClient)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthmanagedapikey.FieldClientID)
	}
	query.Where(predicate.OAuthManagedAPIKey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthclient.OauthManagedAPIKeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClientID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "client_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *OAuthClientQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OAuthClientQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for i := range fields {
			if fields[i] != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OAuthClientQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(oauthclient.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = oauthclient.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *OAuthClientQuery) ForUpdate(opts ...sql.LockOption) *OAuthClientQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *OAuthClientQuery) ForShare(opts ...sql.LockOption) *OAuthClientQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// OAuthClientGroupBy is the group-by builder for OAuthClient entities.
type OAuthClientGroupBy struct {
	selector
	build *OAuthClientQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OAuthClientGroupBy) Aggregate(fns ...AggregateFunc) *OAuthClientGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OAuthClientGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthClientQuery, *OAuthClientGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OAuthClientGroupBy) sqlScan(ctx context.Context, root *OAuthClientQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OAuthClientSelect is the builder for selecting fields of OAuthClient entities.
type OAuthClientSelect struct {
	*OAuthClientQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OAuthClientSelect) Aggregate(fns ...AggregateFunc) *OAuthClientSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OAuthClientSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthClientQuery, *OAuthClientSelect](ctx, _s.OAuthClientQuery, _s, _s.inters, v)
}

func (_s *OAuthClientSelect) sqlScan(ctx context.Context, root *OAuthClientQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
