// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationtransaction"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthAuthorizationTransactionDelete is the builder for deleting a OAuthAuthorizationTransaction entity.
type OAuthAuthorizationTransactionDelete struct {
	config
	hooks    []Hook
	mutation *OAuthAuthorizationTransactionMutation
}

// Where appends a list predicates to the OAuthAuthorizationTransactionDelete builder.
func (_d *OAuthAuthorizationTransactionDelete) Where(ps ...predicate.OAuthAuthorizationTransaction) *OAuthAuthorizationTransactionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthAuthorizationTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthAuthorizationTransactionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthAuthorizationTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthauthorizationtransaction.Table, sqlgraph.NewFieldSpec(oauthauthorizationtransaction.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthAuthorizationTransactionDeleteOne is the builder for deleting a single OAuthAuthorizationTransaction entity.
type OAuthAuthorizationTransactionDeleteOne struct {
	_d *OAuthAuthorizationTransactionDelete
}

// Where appends a list predicates to the OAuthAuthorizationTransactionDelete builder.
func (_d *OAuthAuthorizationTransactionDeleteOne) Where(ps ...predicate.OAuthAuthorizationTransaction) *OAuthAuthorizationTransactionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthAuthorizationTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthauthorizationtransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthAuthorizationTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
