// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/oauthconsent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OAuthConsentUpdate is the builder for updating OAuthConsent entities.
type OAuthConsentUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthConsentMutation
}

// Where appends a list predicates to the OAuthConsentUpdate builder.
func (_u *OAuthConsentUpdate) Where(ps ...predicate.OAuthConsent) *OAuthConsentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthConsentUpdate) SetUpdatedAt(v time.Time) *OAuthConsentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthConsentUpdate) SetUserID(v int64) *OAuthConsentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableUserID(v *int64) *OAuthConsentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthConsentUpdate) SetClientID(v int64) *OAuthConsentUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableClientID(v *int64) *OAuthConsentUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthConsentUpdate) SetScopes(v []string) *OAuthConsentUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthConsentUpdate) AppendScopes(v []string) *OAuthConsentUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthConsentUpdate) SetRevokedAt(v time.Time) *OAuthConsentUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableRevokedAt(v *time.Time) *OAuthConsentUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthConsentUpdate) ClearRevokedAt() *OAuthConsentUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthConsentUpdate) SetUser(v *User) *OAuthConsentUpdate {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthConsentUpdate) SetClient(v *OAuthClient) *OAuthConsentUpdate {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthConsentMutation object of the builder.
func (_u *OAuthConsentUpdate) Mutation() *OAuthConsentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthConsentUpdate) ClearUser() *OAuthConsentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthConsentUpdate) ClearClient() *OAuthConsentUpdate {
	_u.mutation.ClearClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthConsentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthConsentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthConsentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthConsentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthConsentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthconsent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthConsentUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthConsent.user"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthConsent.client"`)
	}
	return nil
}

func (_u *OAuthConsentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthconsent.Table, oauthconsent.Columns, sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthconsent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthconsent.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthconsent.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthconsent.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthconsent.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.UserTable,
			Columns: []string{oauthconsent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.UserTable,
			Columns: []string{oauthconsent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.ClientTable,
			Columns: []string{oauthconsent.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.ClientTable,
			Columns: []string{oauthconsent.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthconsent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthConsentUpdateOne is the builder for updating a single OAuthConsent entity.
type OAuthConsentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthConsentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthConsentUpdateOne) SetUpdatedAt(v time.Time) *OAuthConsentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthConsentUpdateOne) SetUserID(v int64) *OAuthConsentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableUserID(v *int64) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthConsentUpdateOne) SetClientID(v int64) *OAuthConsentUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableClientID(v *int64) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthConsentUpdateOne) SetScopes(v []string) *OAuthConsentUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthConsentUpdateOne) AppendScopes(v []string) *OAuthConsentUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthConsentUpdateOne) SetRevokedAt(v time.Time) *OAuthConsentUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableRevokedAt(v *time.Time) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthConsentUpdateOne) ClearRevokedAt() *OAuthConsentUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthConsentUpdateOne) SetUser(v *User) *OAuthConsentUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_u *OAuthConsentUpdateOne) SetClient(v *OAuthClient) *OAuthConsentUpdateOne {
	return _u.SetClientID(v.ID)
}

// Mutation returns the OAuthConsentMutation object of the builder.
func (_u *OAuthConsentUpdateOne) Mutation() *OAuthConsentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthConsentUpdateOne) ClearUser() *OAuthConsentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearClient clears the "client" edge to the OAuthClient entity.
func (_u *OAuthConsentUpdateOne) ClearClient() *OAuthConsentUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// Where appends a list predicates to the OAuthConsentUpdate builder.
func (_u *OAuthConsentUpdateOne) Where(ps ...predicate.OAuthConsent) *OAuthConsentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthConsentUpdateOne) Select(field string, fields ...string) *OAuthConsentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthConsent entity.
func (_u *OAuthConsentUpdateOne) Save(ctx context.Context) (*OAuthConsent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthConsentUpdateOne) SaveX(ctx context.Context) *OAuthConsent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthConsentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthConsentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthConsentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthconsent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthConsentUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthConsent.user"`)
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthConsent.client"`)
	}
	return nil
}

func (_u *OAuthConsentUpdateOne) sqlSave(ctx context.Context) (_node *OAuthConsent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthconsent.Table, oauthconsent.Columns, sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthConsent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthconsent.FieldID)
		for _, f := range fields {
			if !oauthconsent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthconsent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthconsent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthconsent.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthconsent.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthconsent.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthconsent.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.UserTable,
			Columns: []string{oauthconsent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.UserTable,
			Columns: []string{oauthconsent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.ClientTable,
			Columns: []string{oauthconsent.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthconsent.ClientTable,
			Columns: []string{oauthconsent.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthConsent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthconsent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
