// Code generated by ent, DO NOT EDIT.

package oauthrefreshtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthrefreshtoken type in the database.
	Label = "oauth_refresh_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// FieldHashKeyVersion holds the string denoting the hash_key_version field in the database.
	FieldHashKeyVersion = "hash_key_version"
	// FieldFamilyID holds the string denoting the family_id field in the database.
	FieldFamilyID = "family_id"
	// FieldParentTokenID holds the string denoting the parent_token_id field in the database.
	FieldParentTokenID = "parent_token_id"
	// FieldReplacedByTokenID holds the string denoting the replaced_by_token_id field in the database.
	FieldReplacedByTokenID = "replaced_by_token_id"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldIdleExpiresAt holds the string denoting the idle_expires_at field in the database.
	FieldIdleExpiresAt = "idle_expires_at"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// EdgeChildTokens holds the string denoting the child_tokens edge name in mutations.
	EdgeChildTokens = "child_tokens"
	// EdgeReplacedTokens holds the string denoting the replaced_tokens edge name in mutations.
	EdgeReplacedTokens = "replaced_tokens"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeClient holds the string denoting the client edge name in mutations.
	EdgeClient = "client"
	// EdgeParentToken holds the string denoting the parent_token edge name in mutations.
	EdgeParentToken = "parent_token"
	// EdgeReplacedByToken holds the string denoting the replaced_by_token edge name in mutations.
	EdgeReplacedByToken = "replaced_by_token"
	// Table holds the table name of the oauthrefreshtoken in the database.
	Table = "oauth_refresh_tokens"
	// ChildTokensTable is the table that holds the child_tokens relation/edge.
	ChildTokensTable = "oauth_refresh_tokens"
	// ChildTokensColumn is the table column denoting the child_tokens relation/edge.
	ChildTokensColumn = "parent_token_id"
	// ReplacedTokensTable is the table that holds the replaced_tokens relation/edge.
	ReplacedTokensTable = "oauth_refresh_tokens"
	// ReplacedTokensColumn is the table column denoting the replaced_tokens relation/edge.
	ReplacedTokensColumn = "replaced_by_token_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "oauth_refresh_tokens"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ClientTable is the table that holds the client relation/edge.
	ClientTable = "oauth_refresh_tokens"
	// ClientInverseTable is the table name for the OAuthClient entity.
	// It exists in this package in order to avoid circular dependency with the "oauthclient" package.
	ClientInverseTable = "oauth_clients"
	// ClientColumn is the table column denoting the client relation/edge.
	ClientColumn = "client_id"
	// ParentTokenTable is the table that holds the parent_token relation/edge.
	ParentTokenTable = "oauth_refresh_tokens"
	// ParentTokenColumn is the table column denoting the parent_token relation/edge.
	ParentTokenColumn = "parent_token_id"
	// ReplacedByTokenTable is the table that holds the replaced_by_token relation/edge.
	ReplacedByTokenTable = "oauth_refresh_tokens"
	// ReplacedByTokenColumn is the table column denoting the replaced_by_token relation/edge.
	ReplacedByTokenColumn = "replaced_by_token_id"
)

// Columns holds all SQL columns for oauthrefreshtoken fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTokenHash,
	FieldHashKeyVersion,
	FieldFamilyID,
	FieldParentTokenID,
	FieldReplacedByTokenID,
	FieldScopes,
	FieldIssuedAt,
	FieldExpiresAt,
	FieldIdleExpiresAt,
	FieldLastUsedAt,
	FieldRevokedAt,
	FieldUserID,
	FieldClientID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	TokenHashValidator func(string) error
	// DefaultHashKeyVersion holds the default value on creation for the "hash_key_version" field.
	DefaultHashKeyVersion int
	// DefaultScopes holds the default value on creation for the "scopes" field.
	DefaultScopes func() []string
)

// OrderOption defines the ordering options for the OAuthRefreshToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTokenHash orders the results by the token_hash field.
func ByTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenHash, opts...).ToFunc()
}

// ByHashKeyVersion orders the results by the hash_key_version field.
func ByHashKeyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashKeyVersion, opts...).ToFunc()
}

// ByFamilyID orders the results by the family_id field.
func ByFamilyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamilyID, opts...).ToFunc()
}

// ByParentTokenID orders the results by the parent_token_id field.
func ByParentTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentTokenID, opts...).ToFunc()
}

// ByReplacedByTokenID orders the results by the replaced_by_token_id field.
func ByReplacedByTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplacedByTokenID, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByIdleExpiresAt orders the results by the idle_expires_at field.
func ByIdleExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdleExpiresAt, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByChildTokensCount orders the results by child_tokens count.
func ByChildTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildTokensStep(), opts...)
	}
}

// ByChildTokens orders the results by child_tokens terms.
func ByChildTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReplacedTokensCount orders the results by replaced_tokens count.
func ByReplacedTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReplacedTokensStep(), opts...)
	}
}

// ByReplacedTokens orders the results by replaced_tokens terms.
func ByReplacedTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReplacedTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByClientField orders the results by client field.
func ByClientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientStep(), sql.OrderByField(field, opts...))
	}
}

// ByParentTokenField orders the results by parent_token field.
func ByParentTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentTokenStep(), sql.OrderByField(field, opts...))
	}
}

// ByReplacedByTokenField orders the results by replaced_by_token field.
func ByReplacedByTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReplacedByTokenStep(), sql.OrderByField(field, opts...))
	}
}
func newChildTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildTokensTable, ChildTokensColumn),
	)
}
func newReplacedTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReplacedTokensTable, ReplacedTokensColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newClientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
	)
}
func newParentTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTokenTable, ParentTokenColumn),
	)
}
func newReplacedByTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReplacedByTokenTable, ReplacedByTokenColumn),
	)
}
