// Code generated by ent, DO NOT EDIT.

package oauthrefreshtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldTokenHash, v))
}

// HashKeyVersion applies equality check predicate on the "hash_key_version" field. It's identical to HashKeyVersionEQ.
func HashKeyVersion(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldHashKeyVersion, v))
}

// FamilyID applies equality check predicate on the "family_id" field. It's identical to FamilyIDEQ.
func FamilyID(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldFamilyID, v))
}

// ParentTokenID applies equality check predicate on the "parent_token_id" field. It's identical to ParentTokenIDEQ.
func ParentTokenID(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldParentTokenID, v))
}

// ReplacedByTokenID applies equality check predicate on the "replaced_by_token_id" field. It's identical to ReplacedByTokenIDEQ.
func ReplacedByTokenID(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldReplacedByTokenID, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldIssuedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldExpiresAt, v))
}

// IdleExpiresAt applies equality check predicate on the "idle_expires_at" field. It's identical to IdleExpiresAtEQ.
func IdleExpiresAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldIdleExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldRevokedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldUserID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldClientID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// HashKeyVersionEQ applies the EQ predicate on the "hash_key_version" field.
func HashKeyVersionEQ(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldHashKeyVersion, v))
}

// HashKeyVersionNEQ applies the NEQ predicate on the "hash_key_version" field.
func HashKeyVersionNEQ(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldHashKeyVersion, v))
}

// HashKeyVersionIn applies the In predicate on the "hash_key_version" field.
func HashKeyVersionIn(vs ...int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldHashKeyVersion, vs...))
}

// HashKeyVersionNotIn applies the NotIn predicate on the "hash_key_version" field.
func HashKeyVersionNotIn(vs ...int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldHashKeyVersion, vs...))
}

// HashKeyVersionGT applies the GT predicate on the "hash_key_version" field.
func HashKeyVersionGT(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldHashKeyVersion, v))
}

// HashKeyVersionGTE applies the GTE predicate on the "hash_key_version" field.
func HashKeyVersionGTE(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldHashKeyVersion, v))
}

// HashKeyVersionLT applies the LT predicate on the "hash_key_version" field.
func HashKeyVersionLT(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldHashKeyVersion, v))
}

// HashKeyVersionLTE applies the LTE predicate on the "hash_key_version" field.
func HashKeyVersionLTE(v int) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldHashKeyVersion, v))
}

// FamilyIDEQ applies the EQ predicate on the "family_id" field.
func FamilyIDEQ(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldFamilyID, v))
}

// FamilyIDNEQ applies the NEQ predicate on the "family_id" field.
func FamilyIDNEQ(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldFamilyID, v))
}

// FamilyIDIn applies the In predicate on the "family_id" field.
func FamilyIDIn(vs ...uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldFamilyID, vs...))
}

// FamilyIDNotIn applies the NotIn predicate on the "family_id" field.
func FamilyIDNotIn(vs ...uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldFamilyID, vs...))
}

// FamilyIDGT applies the GT predicate on the "family_id" field.
func FamilyIDGT(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldFamilyID, v))
}

// FamilyIDGTE applies the GTE predicate on the "family_id" field.
func FamilyIDGTE(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldFamilyID, v))
}

// FamilyIDLT applies the LT predicate on the "family_id" field.
func FamilyIDLT(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldFamilyID, v))
}

// FamilyIDLTE applies the LTE predicate on the "family_id" field.
func FamilyIDLTE(v uuid.UUID) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldFamilyID, v))
}

// ParentTokenIDEQ applies the EQ predicate on the "parent_token_id" field.
func ParentTokenIDEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldParentTokenID, v))
}

// ParentTokenIDNEQ applies the NEQ predicate on the "parent_token_id" field.
func ParentTokenIDNEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldParentTokenID, v))
}

// ParentTokenIDIn applies the In predicate on the "parent_token_id" field.
func ParentTokenIDIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldParentTokenID, vs...))
}

// ParentTokenIDNotIn applies the NotIn predicate on the "parent_token_id" field.
func ParentTokenIDNotIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldParentTokenID, vs...))
}

// ParentTokenIDIsNil applies the IsNil predicate on the "parent_token_id" field.
func ParentTokenIDIsNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIsNull(FieldParentTokenID))
}

// ParentTokenIDNotNil applies the NotNil predicate on the "parent_token_id" field.
func ParentTokenIDNotNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotNull(FieldParentTokenID))
}

// ReplacedByTokenIDEQ applies the EQ predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDNEQ applies the NEQ predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDNEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDIn applies the In predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldReplacedByTokenID, vs...))
}

// ReplacedByTokenIDNotIn applies the NotIn predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDNotIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldReplacedByTokenID, vs...))
}

// ReplacedByTokenIDIsNil applies the IsNil predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDIsNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIsNull(FieldReplacedByTokenID))
}

// ReplacedByTokenIDNotNil applies the NotNil predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDNotNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotNull(FieldReplacedByTokenID))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldIssuedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldExpiresAt, v))
}

// IdleExpiresAtEQ applies the EQ predicate on the "idle_expires_at" field.
func IdleExpiresAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldIdleExpiresAt, v))
}

// IdleExpiresAtNEQ applies the NEQ predicate on the "idle_expires_at" field.
func IdleExpiresAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldIdleExpiresAt, v))
}

// IdleExpiresAtIn applies the In predicate on the "idle_expires_at" field.
func IdleExpiresAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldIdleExpiresAt, vs...))
}

// IdleExpiresAtNotIn applies the NotIn predicate on the "idle_expires_at" field.
func IdleExpiresAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldIdleExpiresAt, vs...))
}

// IdleExpiresAtGT applies the GT predicate on the "idle_expires_at" field.
func IdleExpiresAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldIdleExpiresAt, v))
}

// IdleExpiresAtGTE applies the GTE predicate on the "idle_expires_at" field.
func IdleExpiresAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldIdleExpiresAt, v))
}

// IdleExpiresAtLT applies the LT predicate on the "idle_expires_at" field.
func IdleExpiresAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldIdleExpiresAt, v))
}

// IdleExpiresAtLTE applies the LTE predicate on the "idle_expires_at" field.
func IdleExpiresAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldIdleExpiresAt, v))
}

// IdleExpiresAtIsNil applies the IsNil predicate on the "idle_expires_at" field.
func IdleExpiresAtIsNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIsNull(FieldIdleExpiresAt))
}

// IdleExpiresAtNotNil applies the NotNil predicate on the "idle_expires_at" field.
func IdleExpiresAtNotNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotNull(FieldIdleExpiresAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotNull(FieldRevokedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldUserID, vs...))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...int64) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.FieldNotIn(FieldClientID, vs...))
}

// HasChildTokens applies the HasEdge predicate on the "child_tokens" edge.
func HasChildTokens() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildTokensTable, ChildTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildTokensWith applies the HasEdge predicate on the "child_tokens" edge with a given conditions (other predicates).
func HasChildTokensWith(preds ...predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := newChildTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReplacedTokens applies the HasEdge predicate on the "replaced_tokens" edge.
func HasReplacedTokens() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReplacedTokensTable, ReplacedTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReplacedTokensWith applies the HasEdge predicate on the "replaced_tokens" edge with a given conditions (other predicates).
func HasReplacedTokensWith(preds ...predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := newReplacedTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClient applies the HasEdge predicate on the "client" edge.
func HasClient() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientWith applies the HasEdge predicate on the "client" edge with a given conditions (other predicates).
func HasClientWith(preds ...predicate.OAuthClient) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := newClientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParentToken applies the HasEdge predicate on the "parent_token" edge.
func HasParentToken() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTokenTable, ParentTokenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentTokenWith applies the HasEdge predicate on the "parent_token" edge with a given conditions (other predicates).
func HasParentTokenWith(preds ...predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := newParentTokenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReplacedByToken applies the HasEdge predicate on the "replaced_by_token" edge.
func HasReplacedByToken() predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReplacedByTokenTable, ReplacedByTokenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReplacedByTokenWith applies the HasEdge predicate on the "replaced_by_token" edge with a given conditions (other predicates).
func HasReplacedByTokenWith(preds ...predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(func(s *sql.Selector) {
		step := newReplacedByTokenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthRefreshToken) predicate.OAuthRefreshToken {
	return predicate.OAuthRefreshToken(sql.NotPredicates(p))
}
