// Code generated by ent, DO NOT EDIT.

package oauthauthorizationtransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// TransactionID applies equality check predicate on the "transaction_id" field. It's identical to TransactionIDEQ.
func TransactionID(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldTransactionID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldRedirectURI, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldState, v))
}

// CodeChallenge applies equality check predicate on the "code_challenge" field. It's identical to CodeChallengeEQ.
func CodeChallenge(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeMethod applies equality check predicate on the "code_challenge_method" field. It's identical to CodeChallengeMethodEQ.
func CodeChallengeMethod(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// BrowserSessionHash applies equality check predicate on the "browser_session_hash" field. It's identical to BrowserSessionHashEQ.
func BrowserSessionHash(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldBrowserSessionHash, v))
}

// CsrfTokenHash applies equality check predicate on the "csrf_token_hash" field. It's identical to CsrfTokenHashEQ.
func CsrfTokenHash(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCsrfTokenHash, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldConsumedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldClientID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// TransactionIDEQ applies the EQ predicate on the "transaction_id" field.
func TransactionIDEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldTransactionID, v))
}

// TransactionIDNEQ applies the NEQ predicate on the "transaction_id" field.
func TransactionIDNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldTransactionID, v))
}

// TransactionIDIn applies the In predicate on the "transaction_id" field.
func TransactionIDIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldTransactionID, vs...))
}

// TransactionIDNotIn applies the NotIn predicate on the "transaction_id" field.
func TransactionIDNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldTransactionID, vs...))
}

// TransactionIDGT applies the GT predicate on the "transaction_id" field.
func TransactionIDGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldTransactionID, v))
}

// TransactionIDGTE applies the GTE predicate on the "transaction_id" field.
func TransactionIDGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldTransactionID, v))
}

// TransactionIDLT applies the LT predicate on the "transaction_id" field.
func TransactionIDLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldTransactionID, v))
}

// TransactionIDLTE applies the LTE predicate on the "transaction_id" field.
func TransactionIDLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldTransactionID, v))
}

// TransactionIDContains applies the Contains predicate on the "transaction_id" field.
func TransactionIDContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldTransactionID, v))
}

// TransactionIDHasPrefix applies the HasPrefix predicate on the "transaction_id" field.
func TransactionIDHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldTransactionID, v))
}

// TransactionIDHasSuffix applies the HasSuffix predicate on the "transaction_id" field.
func TransactionIDHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldTransactionID, v))
}

// TransactionIDEqualFold applies the EqualFold predicate on the "transaction_id" field.
func TransactionIDEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldTransactionID, v))
}

// TransactionIDContainsFold applies the ContainsFold predicate on the "transaction_id" field.
func TransactionIDContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldTransactionID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldRedirectURI, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldState, v))
}

// CodeChallengeEQ applies the EQ predicate on the "code_challenge" field.
func CodeChallengeEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeNEQ applies the NEQ predicate on the "code_challenge" field.
func CodeChallengeNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldCodeChallenge, v))
}

// CodeChallengeIn applies the In predicate on the "code_challenge" field.
func CodeChallengeIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldCodeChallenge, vs...))
}

// CodeChallengeNotIn applies the NotIn predicate on the "code_challenge" field.
func CodeChallengeNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldCodeChallenge, vs...))
}

// CodeChallengeGT applies the GT predicate on the "code_challenge" field.
func CodeChallengeGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldCodeChallenge, v))
}

// CodeChallengeGTE applies the GTE predicate on the "code_challenge" field.
func CodeChallengeGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldCodeChallenge, v))
}

// CodeChallengeLT applies the LT predicate on the "code_challenge" field.
func CodeChallengeLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldCodeChallenge, v))
}

// CodeChallengeLTE applies the LTE predicate on the "code_challenge" field.
func CodeChallengeLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldCodeChallenge, v))
}

// CodeChallengeContains applies the Contains predicate on the "code_challenge" field.
func CodeChallengeContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldCodeChallenge, v))
}

// CodeChallengeHasPrefix applies the HasPrefix predicate on the "code_challenge" field.
func CodeChallengeHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldCodeChallenge, v))
}

// CodeChallengeHasSuffix applies the HasSuffix predicate on the "code_challenge" field.
func CodeChallengeHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldCodeChallenge, v))
}

// CodeChallengeEqualFold applies the EqualFold predicate on the "code_challenge" field.
func CodeChallengeEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldCodeChallenge, v))
}

// CodeChallengeContainsFold applies the ContainsFold predicate on the "code_challenge" field.
func CodeChallengeContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldCodeChallenge, v))
}

// CodeChallengeMethodEQ applies the EQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodNEQ applies the NEQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodIn applies the In predicate on the "code_challenge_method" field.
func CodeChallengeMethodIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodNotIn applies the NotIn predicate on the "code_challenge_method" field.
func CodeChallengeMethodNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodGT applies the GT predicate on the "code_challenge_method" field.
func CodeChallengeMethodGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodGTE applies the GTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLT applies the LT predicate on the "code_challenge_method" field.
func CodeChallengeMethodLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLTE applies the LTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContains applies the Contains predicate on the "code_challenge_method" field.
func CodeChallengeMethodContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasPrefix applies the HasPrefix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasSuffix applies the HasSuffix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodEqualFold applies the EqualFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContainsFold applies the ContainsFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldCodeChallengeMethod, v))
}

// BrowserSessionHashEQ applies the EQ predicate on the "browser_session_hash" field.
func BrowserSessionHashEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldBrowserSessionHash, v))
}

// BrowserSessionHashNEQ applies the NEQ predicate on the "browser_session_hash" field.
func BrowserSessionHashNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldBrowserSessionHash, v))
}

// BrowserSessionHashIn applies the In predicate on the "browser_session_hash" field.
func BrowserSessionHashIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldBrowserSessionHash, vs...))
}

// BrowserSessionHashNotIn applies the NotIn predicate on the "browser_session_hash" field.
func BrowserSessionHashNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldBrowserSessionHash, vs...))
}

// BrowserSessionHashGT applies the GT predicate on the "browser_session_hash" field.
func BrowserSessionHashGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldBrowserSessionHash, v))
}

// BrowserSessionHashGTE applies the GTE predicate on the "browser_session_hash" field.
func BrowserSessionHashGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldBrowserSessionHash, v))
}

// BrowserSessionHashLT applies the LT predicate on the "browser_session_hash" field.
func BrowserSessionHashLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldBrowserSessionHash, v))
}

// BrowserSessionHashLTE applies the LTE predicate on the "browser_session_hash" field.
func BrowserSessionHashLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldBrowserSessionHash, v))
}

// BrowserSessionHashContains applies the Contains predicate on the "browser_session_hash" field.
func BrowserSessionHashContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldBrowserSessionHash, v))
}

// BrowserSessionHashHasPrefix applies the HasPrefix predicate on the "browser_session_hash" field.
func BrowserSessionHashHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldBrowserSessionHash, v))
}

// BrowserSessionHashHasSuffix applies the HasSuffix predicate on the "browser_session_hash" field.
func BrowserSessionHashHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldBrowserSessionHash, v))
}

// BrowserSessionHashEqualFold applies the EqualFold predicate on the "browser_session_hash" field.
func BrowserSessionHashEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldBrowserSessionHash, v))
}

// BrowserSessionHashContainsFold applies the ContainsFold predicate on the "browser_session_hash" field.
func BrowserSessionHashContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldBrowserSessionHash, v))
}

// CsrfTokenHashEQ applies the EQ predicate on the "csrf_token_hash" field.
func CsrfTokenHashEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldCsrfTokenHash, v))
}

// CsrfTokenHashNEQ applies the NEQ predicate on the "csrf_token_hash" field.
func CsrfTokenHashNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldCsrfTokenHash, v))
}

// CsrfTokenHashIn applies the In predicate on the "csrf_token_hash" field.
func CsrfTokenHashIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldCsrfTokenHash, vs...))
}

// CsrfTokenHashNotIn applies the NotIn predicate on the "csrf_token_hash" field.
func CsrfTokenHashNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldCsrfTokenHash, vs...))
}

// CsrfTokenHashGT applies the GT predicate on the "csrf_token_hash" field.
func CsrfTokenHashGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldCsrfTokenHash, v))
}

// CsrfTokenHashGTE applies the GTE predicate on the "csrf_token_hash" field.
func CsrfTokenHashGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldCsrfTokenHash, v))
}

// CsrfTokenHashLT applies the LT predicate on the "csrf_token_hash" field.
func CsrfTokenHashLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldCsrfTokenHash, v))
}

// CsrfTokenHashLTE applies the LTE predicate on the "csrf_token_hash" field.
func CsrfTokenHashLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldCsrfTokenHash, v))
}

// CsrfTokenHashContains applies the Contains predicate on the "csrf_token_hash" field.
func CsrfTokenHashContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldCsrfTokenHash, v))
}

// CsrfTokenHashHasPrefix applies the HasPrefix predicate on the "csrf_token_hash" field.
func CsrfTokenHashHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldCsrfTokenHash, v))
}

// CsrfTokenHashHasSuffix applies the HasSuffix predicate on the "csrf_token_hash" field.
func CsrfTokenHashHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldCsrfTokenHash, v))
}

// CsrfTokenHashEqualFold applies the EqualFold predicate on the "csrf_token_hash" field.
func CsrfTokenHashEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldCsrfTokenHash, v))
}

// CsrfTokenHashContainsFold applies the ContainsFold predicate on the "csrf_token_hash" field.
func CsrfTokenHashContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldCsrfTokenHash, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotNull(FieldUserID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotNull(FieldConsumedAt))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...int64) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.FieldNotIn(FieldClientID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClient applies the HasEdge predicate on the "client" edge.
func HasClient() predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientWith applies the HasEdge predicate on the "client" edge with a given conditions (other predicates).
func HasClientWith(preds ...predicate.OAuthClient) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(func(s *sql.Selector) {
		step := newClientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthAuthorizationTransaction) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthAuthorizationTransaction) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthAuthorizationTransaction) predicate.OAuthAuthorizationTransaction {
	return predicate.OAuthAuthorizationTransaction(sql.NotPredicates(p))
}
